CASMNET-1165 Complete adding edge routers to SLS - allow qty adjustment
Cray-HPE/docs-csm pull request #1022
Opened 2022-03-04 01:41 UTC by trad511

## Summary and Scope

CASMNET-693 included every requirement of CASMNET-1165.  This completes CASMNET-1165 by allowing adjustment of the number of edge routers, for test and development environments.  This only adds optional new flag of `--number-of-chn-edge-switches` with a default value of 2 (as seen on most normal environments.

## Issues and Related PRs

* Resolves [CASMNET-1165](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1165)

## Testing

Tested by adjusting data using Surtur and Wasp input.  Wasp is an actual use case for this.

## Risks and Mitigations

None, this is an override with "normal system" defaults.

2022-03-04 21:01 UTC, johren-hpe approved these changes

2022-04-24 00:07 UTC, mharding-hpe requested changes
This needs to be rebased and have its conflicts resolved in order for it to be reviewed.

2022-06-10 18:46 UTC, rustydb approved these changes

2022-06-16 17:54 UTC, mharding-hpe commented
The merge conflicts still need to be resolved before this can be reviewed.

2022-06-16 21:42 UTC, closed without merging

2022-06-16 21:43 UTC, trad511 commented
Closing this as a much later PR was merged before this and included the fix presented here.