CASMPET-5263 Add keycloak admin password change doc
Cray-HPE/docs-csm pull request #1054
Opened 2022-03-07 22:50 UTC by kburns-hpe

This adds the documentation on how to change the keycloak admin password.

2022-03-07 22:58 UTC, rgross727 requested changes

2022-03-07 22:58 UTC, rgross727 commented on operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
> +    If the above command complaints that it cannot find certs/sealed_secrets.crt then you can run the following commands to create it
complaints => complains

2022-03-07 23:16 UTC, kburns-hpe commented on operations/security_and_authentication/Change_the_Keycloak_Admin_Password.md
> +    If the above command complaints that it cannot find certs/sealed_secrets.crt then you can run the following commands to create it
Fixed.

2022-03-07 23:32 UTC, rgross727 approved these changes

2022-03-14 19:58 UTC, gbaker-hpe approved these changes

2022-03-14 19:58 UTC, merged