CASMNET-1203 - Remove incomplete procedure to update system domain post-installation.
Cray-HPE/docs-csm pull request #1073
Opened 2022-03-10 01:01 UTC by spillerc-hpe

## Summary and Scope

The procedure to change the system domain name post-install is incomplete and has not been properly tested.

For example step 7 "Generate and install new certificates for Istio" contains no instructions for generating or installing new certificates.

This procedure should be removed from the documentation until changing the system domain name can be supported.

## Issues and Related PRs

* Resolves [CASMNET-1203](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1203)

## Testing

### Tested on:

  * Local development environment

### Test description:

## Risks and Mitigations

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [X] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-03-10 14:20 UTC, nrockershousen approved these changes

2022-03-10 20:37 UTC, gbaker-hpe commented
@spillerc-hpe this looks good but there is a broken link detected on the main branch.  Would you please investigate to see if this is a real error?

2022-03-10 20:37 UTC, gbaker-hpe requested changes
There is a broken link detected on the main branch.  Would you please investigate to see if this is a real error?

2022-03-10 21:59 UTC, spillerc-hpe commented
@gbaker-hpe the broken link was genuine, I have removed the second reference to the procedure I removed.

2022-03-11 20:56 UTC, gbaker-hpe approved these changes

2022-03-11 21:30 UTC, merged