CASMTRIAGE-3101
Cray-HPE/docs-csm pull request #1085
Opened 2022-03-11 19:25 UTC by lukebates123

## Summary and Scope

Link net docs to `Add_a_Standard_Rack_Node.md` procedure

2022-04-24 00:05 UTC, mharding-hpe requested changes

2022-04-24 00:05 UTC, mharding-hpe commented on operations/node_management/Add_a_Standard_Rack_Node.md
> +3.
Should this line be here? If this is a list item, it needs text following it.

2022-04-24 00:05 UTC, mharding-hpe commented on operations/node_management/Add_a_Standard_Rack_Node.md
> +- UAN with Aruba.  Depending on the architecture the UAN could connect to either an aggregation or a spine switch.
```suggestion
- UAN with Aruba.  Depending on the architecture, the UAN could connect to either an aggregation or a spine switch.
```

2022-07-12 20:18 UTC, rustydb commented
/backport release/1.2 main

2022-07-12 20:29 UTC, kosonenj approved these changes

2022-07-12 21:24 UTC, rustydb approved these changes

2022-07-12 21:24 UTC, merged