CASMINST-4219 - Add instructions to merge in new CSM 1.2 VCS content to upgrade procedure
Cray-HPE/docs-csm pull request #1086
Opened 2022-03-14 10:43 UTC by spillerc-hpe

## Summary and Scope

A CSM upgrade can introduce new content to the CSM configuration management repository.

It is necessary to merge this content into any working branch then update the CFS configuration used for NCN personalization to ensure this new Ansible content is applied.

## Issues and Related PRs

* Resolves [CASMINST-4219](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4219)

## Testing

### Tested on:

  * `hela`

### Test description:

Procedure tested on hela.

## Risks and Mitigations

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [X] Target branch correct
- [ ] CHANGELOG.md updated
- [X] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-03-14 18:16 UTC, nrockershousen commented on upgrade/1.2/Stage_3.md
> +1. Obtain import_branch of new release from the cray-product-catalog Kubernetes ConfigMap
```suggestion
1. Obtain import_branch of new release from the cray-product-catalog Kubernetes ConfigMap
```
```suggestion
1. Obtain import_branch of new release from the cray-product-catalog Kubernetes ConfigMap.
```

2022-03-14 18:16 UTC, nrockershousen commented on upgrade/1.2/Stage_3.md
> +## Update the CSM configuration management repository
```suggestion
## Update the CSM Configuration Management Repository
```

2022-03-14 18:16 UTC, nrockershousen commented on upgrade/1.2/Stage_3.md
> +## Update the CSM configuration management repository
```suggestion
## Update the CSM Configuration Management Repository
```

2022-03-14 18:16 UTC, nrockershousen commented on upgrade/1.2/Stage_3.md
> +   In the below example the import branch is `cray/csm/1.9.21`
```suggestion
   In the following example, the import branch is `cray/csm/1.9.21`.
```

2022-03-14 18:16 UTC, nrockershousen commented on upgrade/1.2/Stage_3.md
> +   In the below example the import branch is `cray/csm/1.9.21`
```suggestion
   In the following example, the import branch is `cray/csm/1.9.21`.
```

2022-03-14 18:16 UTC, nrockershousen commented on upgrade/1.2/Stage_3.md
> +   Please follow the procedure from [Perform\_NCN\_Personalization.md](../../operations/CSM_product_management/Perform_NCN_Personalization.md) to update the CFS configuration and run NCN Personalizat
```suggestion
   Refer to the [Perform NCN Personalization](../../operations/CSM_product_management/Perform_NCN_Personalization.md) procedure to update the CFS configuration and run NCN Personalization.
```

2022-03-14 18:16 UTC, nrockershousen commented on upgrade/1.2/Stage_3.md
> +   Please follow the procedure from [Perform\_NCN\_Personalization.md](../../operations/CSM_product_management/Perform_NCN_Personalization.md) to update the CFS configuration and run NCN Personalizat
```suggestion
   Refer to the [Perform NCN Personalization](../../operations/CSM_product_management/Perform_NCN_Personalization.md) procedure to update the CFS configuration and run NCN Personalization.
```

2022-03-14 20:31 UTC, gbaker-hpe approved these changes

2022-03-14 20:47 UTC, rkleinman-hpe requested changes
Please hold off on merging this until we determine if CASMCMS-7890 will make it unnecessary.

2022-03-15 15:11 UTC, closed without merging

2022-03-15 15:12 UTC, spillerc-hpe commented
Closing as this will be handled via [CASMINST-4218](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4218)