CASMMON-119:CPU THROTTLING - smartmon pods
Cray-HPE/docs-csm pull request #1091
Opened 2022-03-15 06:28 UTC by rambabubolla

Summary and Scope
CPU THROTTLING - smartmon pods
Issues and Related PRs
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-119
Testing
No new code, just documentation

Test description:
-NA

2022-03-15 15:28 UTC, nrockershousen commented on operations/system_management_health/Troubleshoot_Prometheus_Alerts.md
> +Alerts for CPUThrottlingHigh on smartmon pods can be ignored. it is normal for smartmon pods resource usage to spike when it is polling.
```suggestion
Alerts for CPUThrottlingHigh on smartmon pods can be ignored. It is normal for smartmon pods resource usage to spike when it is polling.
```

2022-04-24 00:04 UTC, mharding-hpe requested changes
This needs to be rebased and have its conflicts resolved, in order to be reviewed

2022-06-10 18:45 UTC, rustydb approved these changes

2022-06-16 17:56 UTC, mharding-hpe commented
The proposed text already exists in the main branch. Closing this PR.

2022-06-16 17:56 UTC, closed without merging