STP-3076: Dell management network topics
Cray-HPE/docs-csm pull request #1230
Opened 2022-04-01 13:14 UTC by nrockershousen

## Summary and Scope

No major content changes. These edits are aligned with what was done for the top-level topics and Aruba topics. Here is a general list of changes:
- Organization of content
- Several procedures are currently formatted as topics without steps
- Grammar and formatting
- Unclear steps/instructions

## Issues and Related PRs

* Resolves [STP-3076](https://jira-pro.its.hpecorp.net:8443/browse/STP-3076)
* Change will also be needed in `<main>` and `<release/1.2.5>`

## Testing

N/A

### Tested on:

N/A

### Test description:

N/A

## Risks and Mitigations

None.

2022-04-13 22:00 UTC, mharding-hpe commented
This needs to be rebased. Also, note that it is now targeted for the main branch. This is appropriate -- just be sure to backport or cherry-pick it into all appropriate release branches.

2022-04-15 16:09 UTC, lukebates123 approved these changes

2022-04-19 13:11 UTC, nrockershousen commented
/backport release/1.2

2022-04-19 13:17 UTC, nrockershousen commented
/backport release/1.2

2022-04-24 00:00 UTC, mharding-hpe requested changes

2022-04-24 00:00 UTC, mharding-hpe commented on operations/network/management_network/dell/vlan_trunking_8021q.md
>  A trunk port carries packets on one or more VLANs specified. Packet that ingress on a trunk port are in the VLAN specified in its 802.1Q header, or native VLAN if the packet has no 802.1Q header. A p
```suggestion
A trunk port carries packets on one or more specified VLANs. Packet that ingress on a trunk port are in the VLAN specified in its 802.1Q header, or native VLAN if the packet has no 802.1Q header. A packet that egresses through a trunk port will have an 802.1Q header if it has a nonzero VLAN ID. Any packet that ingresses on a trunk port tagged with a VLAN that the port does not trunk is dropped.
```

2022-04-24 00:00 UTC, mharding-hpe commented on operations/network/management_network/dell/vlan_trunking_8021q.md
```suggestion
```

2022-04-28 13:52 UTC, nrockershousen commented
The backport for this ticket was merged prematurely. Opening up a new PR for release/1.2.

2022-04-28 13:52 UTC, nrockershousen commented
/backport release/1.2

2022-05-02 21:15 UTC, mharding-hpe approved these changes

2022-06-07 19:20 UTC, rustydb commented
/backport release/1.2

2022-06-07 19:52 UTC, merged