Add setting BMC roles to upgrade instructions
Cray-HPE/docs-csm pull request #1429
Opened 2022-04-22 18:29 UTC by alvarez3-hpe

## Summary and Scope

Add instructions for verifying that BMCs of NCNs have the Management role in HSM and setting them as Management if they are not.

## Issues and Related PRs

* Resolves [CASMINST-4503](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4503)

## Testing

### Tested on:

  * loki

### Test description:

Manually tested the commands that were added on loki 

## Risks and Mitigations

None

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-04-22 18:46 UTC, rsjostrand-hpe approved these changes

2022-04-23 19:47 UTC, mharding-hpe requested changes
The same changes as from the main branch PR are needed here:
https://github.com/Cray-HPE/docs-csm/pull/1430

2022-04-25 15:33 UTC, nrockershousen requested changes

2022-04-25 15:33 UTC, nrockershousen commented on upgrade/1.2/Stage_0_Prerequisites.md
> +For more information about setting NCN BMC roles see [Set BMC Management Role](../../operations/hardware_state_manager/Set_BMC_Management_Role.md)
```suggestion
For more information about setting NCN BMC roles, see [Set BMC Management Role](../../operations/hardware_state_manager/Set_BMC_Management_Role.md).
```

2022-04-25 15:33 UTC, nrockershousen commented on upgrade/1.2/Stage_0_Prerequisites.md
> +For more information about locking NCNs and their BMCs see [Lock and Unlock Nodes](../../operations/hardware_state_manager/Lock_and_Unlock_Management_Nodes.md)
```suggestion
For more information about locking NCNs and their BMCs, see [Lock and Unlock Nodes](../../operations/hardware_state_manager/Lock_and_Unlock_Management_Nodes.md).
```

2022-04-25 15:33 UTC, nrockershousen commented on upgrade/1.2/Stage_0_Prerequisites.md
> +1. Run the following command to ensure they're all locked (NCNs and their BMCs).
```suggestion
1. Ensure the NCNs and their BMCs are all locked.
```

2022-04-25 15:33 UTC, nrockershousen commented on upgrade/1.2/Stage_0_Prerequisites.md
> +1. Run the following command to ensure that the roles are properly set.
```suggestion
1. Ensure that the roles in HSM are properly set.
```

2022-04-25 19:33 UTC, nrockershousen approved these changes

2022-04-26 18:16 UTC, mharding-hpe approved these changes

2022-04-26 19:53 UTC, merged