Add setting BMC roles to upgrade instructions Main
Cray-HPE/docs-csm pull request #1430
Opened 2022-04-22 18:55 UTC by alvarez3-hpe

## Summary and Scope

Add instructions for verifying that BMCs of NCNs have the Management role in HSM and setting them as Management if they are not.

## Issues and Related PRs

* Resolves [CASMINST-4503](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4503)

## Testing

### Tested on:

  * loki

### Test description:

Manually tested the commands that were added on loki 

## Risks and Mitigations

None

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-04-23 03:03 UTC, mharding-hpe requested changes
Also, once this PR receives the necessary approvals, we will need the backport PR to 1.2, unless this is intended for only csm-1.3.

2022-04-23 03:03 UTC, mharding-hpe commented on upgrade/1.2/Stage_0_Prerequisites.md
> +    ncn-m001# cray hsm state components query create --format json --component-ids $(cray hsm state components list --role management --type node --format json | jq -r .Components[].ID | sed 's/n[0-9
```suggestion
    ncn-m001# cray hsm state components query create --format json --component-ids \
                            $(cray hsm state components list --role management --type node --format json | \
                                jq -r .Components[].ID | sed 's/n[0-9]*//' | tr '\n' ',' | sed 's/.$//') | \
                                jq '.Components[] | "\(.ID) Role=\(.Role)"'
```

2022-04-23 03:03 UTC, mharding-hpe commented on upgrade/1.2/Stage_0_Prerequisites.md
> +    "x3000c0s8b0 Role=Management"
```suggestion
    ```

    Expected output looks similar to the following:

    ```
    "x3000c0s8b0 Role=Management"
```

2022-04-23 03:03 UTC, mharding-hpe commented on upgrade/1.2/Stage_0_Prerequisites.md
> +1. Run the following command to ensure they're all locked (NCNs and their BMCs).
```suggestion
1. Run the following command to ensure that they are all locked (NCNs and their BMCs).
```

2022-04-23 03:03 UTC, mharding-hpe commented on upgrade/1.2/Stage_0_Prerequisites.md
> +    ```
```suggestion
    ```bash
```

2022-04-23 03:03 UTC, mharding-hpe commented on upgrade/1.2/Stage_0_Prerequisites.md
> +    ```
```suggestion
    ```bash
```

2022-04-23 03:03 UTC, mharding-hpe commented on upgrade/1.2/Stage_0_Prerequisites.md
> +For more information about setting NCN BMC roles see [Set BMC Management Role](../../operations/hardware_state_manager/Set_BMC_Management_Role.md)
```suggestion
For more information about setting NCN BMC roles, see [Set BMC Management Role](../../operations/hardware_state_manager/Set_BMC_Management_Role.md).
```

2022-04-23 03:03 UTC, mharding-hpe commented on upgrade/1.2/Stage_0_Prerequisites.md
> +For more information about locking NCNs and their BMCs see [Lock and Unlock Nodes](../../operations/hardware_state_manager/Lock_and_Unlock_Management_Nodes.md)
```suggestion
For more information about locking NCNs and their BMCs, see [Lock and Unlock Nodes](../../operations/hardware_state_manager/Lock_and_Unlock_Management_Nodes.md).
```

2022-04-25 19:33 UTC, nrockershousen approved these changes

2022-04-26 18:15 UTC, mharding-hpe approved these changes

2022-04-26 19:53 UTC, merged