Added Grafana_Dashboards_by_Component.md documentation
Cray-HPE/docs-csm pull request #1434
Opened 2022-04-22 20:16 UTC by mantoanibroadwing

Added Grafana Dashboard documentation

2022-04-23 02:42 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +## _This document show dashboards available per component in Grafana_
This is not really a heading. This should just be body text. 
```suggestion

This document show the dashboards that are available for each component in Grafana.
```

2022-04-23 02:44 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +_NOTE: There are some known issues around some of the grafana dashboards, and those are explained in [Troubleshoot_Grafana_Dashboard.md](./Troubleshoot_Grafana_Dashboard.md)._
Grafana should be capitalized.
```suggestion
**NOTE:** There are some known issues around some of the Grafana dashboards; those are explained in [Troubleshoot_Grafana_Dashboard.md](./Troubleshoot_Grafana_Dashboard.md).
```

2022-04-23 02:45 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +##### CoreDNS Dashboard
```suggestion
### CoreDNS
```

2022-04-23 02:45 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +##### ETCD Dashboard
```suggestion
### ETCD
```

2022-04-23 02:47 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +##### Kea
```suggestion
### Kea
```

2022-04-23 02:47 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +##### Kubernetes
```suggestion
### Kubernetes
```

2022-04-23 02:47 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +- Ceph - Cluster
Line with Dashboard, since this list is already for Ceph, no need to include it on each item
```suggestion
- Cluster
```

2022-04-23 02:49 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +- Ceph - Host Overview
Similarly, Ceph should be removed from all of the other items in this list.

2022-04-23 02:49 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +- Istio Mesh Dashboard
As with Ceph, Istio should be removed from all of the items in this list.

2022-04-23 02:49 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +- Kubernetes / API server
As with Ceph, Kubernetes should be removed from all of the items in this list.

2022-04-23 02:49 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +##### Nodes
```suggestion
### Nodes
```

2022-04-23 02:50 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +##### Postgres
```suggestion
### Postgres
```

2022-04-23 02:50 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +##### Prometheus
```suggestion
### Prometheus
```

2022-04-23 02:50 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +##### Use Method
```suggestion
### Use Method
```

2022-04-23 02:50 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +- USE Method / Cluster
As with Ceph, USE Method should be removed from all of the items in this list.

2022-04-26 18:28 UTC, mharding-hpe requested changes

2022-04-26 18:28 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +## Dashboards
```suggestion

## Dashboards
```

2022-04-26 18:28 UTC, mharding-hpe commented on operations/system_management_health/Grafana_Dashboards_by_Component.md
> +- Cluster
```suggestion

- Cluster
```

2022-04-26 18:28 UTC, mharding-hpe commented on troubleshooting/index.md
> +### Grafana Dashboards
```suggestion
```

2022-04-26 18:28 UTC, mharding-hpe commented on troubleshooting/index.md
> +
```suggestion
```

2022-04-26 18:28 UTC, mharding-hpe commented on troubleshooting/index.md
> +* [Grafana Dashboards](../operations/system_management_health/Grafana_Dashboards_by_Component.md)
```suggestion
```

2022-04-26 18:28 UTC, mharding-hpe commented on troubleshooting/index.md
> +* [Troubleshoot Grafana Dashboard](../operations/system_management_health/Troubleshoot_Grafana_Dashboard.md)
```suggestion
```

2022-04-26 18:28 UTC, mharding-hpe commented on troubleshooting/index.md
>   * Troubleshoot Kubernetes
```suggestion
 * [Grafana Dashboards](../operations/system_management_health/Grafana_Dashboards_by_Component.md)
    * [Troubleshoot Grafana Dashboard](../operations/system_management_health/Troubleshoot_Grafana_Dashboard.md)
 * Troubleshoot Kubernetes
```

2022-04-26 18:32 UTC, mharding-hpe requested changes
In addition to the changes requested, this needs to be rebased again. I will want to re-review it after the rebase and the changes have been addressed. Also, once this does have the necessary approvals, we will need a backport PR to main (also also 1.0, if applicable)

2022-04-27 16:04 UTC, mharding-hpe requested changes
As before, I will want to re-review before this merges.

2022-06-16 18:15 UTC, mharding-hpe approved these changes

2022-06-16 18:15 UTC, mharding-hpe commented
/backport main

2022-06-16 18:25 UTC, mharding-hpe commented
/backport main

2022-06-16 18:30 UTC, mharding-hpe commented
I created the main branch backport for this: https://github.com/Cray-HPE/docs-csm/pull/1858
If this PR applies to csm-1.0, need a backport there.

2022-06-27 18:39 UTC, rustydb approved these changes

2022-06-28 19:10 UTC, merged