CASMINST-4509: Clarify CSM versions in disk wipe procedure
Cray-HPE/docs-csm pull request #1447
Opened 2022-04-25 17:41 UTC by mharding-hpe

## Summary and Scope

The disk wipe procedure referred to versions 1.4 and 1.5 without saying whether that was CSM or Shasta (or something else). Since we no longer use the Shasta versions normally, I updated the document so it clearly stated the appropriate CSM versions.

I also did an overall linting of the page, correcting a number of small errors, and making some things clearer.

## Issues and Related PRs

## Testing

None. No processes were changed.

## Risks and Mitigations

Low risk.

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [X] License file intact
- [X] Target branch correct
- [ ] CHANGELOG.md updated
- [X] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-04-25 17:41 UTC, mharding-hpe commented
/backport release/1.2 release/1.0

2022-04-25 17:53 UTC, johren-hpe requested changes

2022-04-25 17:53 UTC, johren-hpe commented on install/wipe_ncn_disks_for_reinstallation.md
> +**IMPORTANT:** For each step, oay attention to whether the command is to be run on a master node, storage node, or worker node. If
typo:  oay -> pay

2022-04-25 17:53 UTC, johren-hpe commented on install/wipe_ncn_disks_for_reinstallation.md
> +### Full-Wipe
This should be the same level as Basic Wipe and Advanced Wipe

```
## Full-Wipe
```

2022-04-25 18:01 UTC, johren-hpe approved these changes

2022-04-25 18:14 UTC, mharding-hpe commented
/backport release/1.2

2022-04-27 18:55 UTC, nrockershousen approved these changes

2022-04-27 19:37 UTC, merged