Casminst 3137
Cray-HPE/docs-csm pull request #148
Opened 2021-09-29 13:38 UTC by cdelatte-hpe

2021-09-29 13:42 UTC, kimjensen-hpe approved these changes

2021-09-29 13:47 UTC, brantk-hpe approved these changes

2021-09-29 13:47 UTC, brantk-hpe commented on install/deploy_management_nodes.md
> +    ```bash
this doesn't contain a bash script.

2021-09-29 13:47 UTC, brantk-hpe commented on install/deploy_management_nodes.md
> +1. Wipe the drive `ONLY after you have confirmed the drive is not being used by the current Ceph cluster` via options 1, 2, or both.
Is the goal to emphasize the text? Should be using bold or italics not monospace.

2021-09-29 13:49 UTC, bo-quan requested changes
Some typos and minor suggestion

2021-09-29 13:49 UTC, bo-quan commented on install/deploy_management_nodes.md
> +   **`IMPORTANT:`** If the returned number of OSDs is == total_osds calulated, then you can skip the following steps.  If not, then please proceed with the below additional checks and remdiation step
```suggestion
   **`IMPORTANT:`** If the returned number of OSDs is equal to total_osds calculated, then you can skip the following steps.  If not, then please proceed with the below additional checks and remediation steps.
```

2021-09-29 13:49 UTC, bo-quan commented on install/deploy_management_nodes.md
> +    If the numbers are equal, but less than the `total_osds` calulated, then you may need to fail your `ceph-mgr` daemon to get a fresh inventory.
```suggestion
    If the numbers are equal, but less than the `total_osds` calculated, then you may need to fail your `ceph-mgr` daemon to get a fresh inventory.
```

2021-09-30 13:36 UTC, bo-quan approved these changes

2021-09-30 19:37 UTC, denniswalker approved these changes

2021-10-01 21:14 UTC, merged