CASMHMS-5522: NCN Remove changed stop REDS
Cray-HPE/docs-csm pull request #1530
Opened 2022-05-04 17:21 UTC by shunr-hpe

## Summary and Scope

Changed the documentation to have the user shutdown cray-reds before
doing the remove. And added a note that the BSS restart may timeout if
there are only 2 ncn workers.

There was a race condition where cray-reds would add back a component
to HSM while the remove_management_ncn.py was removing the component
from BSS, SLS, and HSM.

Added a default ipmi username to ncn_status.py. This makes the script
match the documentation.

## Issues and Related PRs

* Resolves [CASMHMS-5522](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5522)

## Testing

_List the environments in which these changes were tested._

### Tested on:

The ncn_status.py changes were tested on

  * baldar - csm 1.0.1
  * fanta - csm 1.2.0-beta.104
  * wasp - csm 1.2.0-beta.102

### Test description:

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No, NA 
- Were continuous integration tests run? If not, why? No, NA
- Was upgrade tested? If not, why? No, NA
- Was downgrade tested? If not, why? No, NA
- Were new tests (or test issues/Jiras) created for this change? No, there are not tests for these scripts

## Risks and Mitigations

The risks are low. The documentation changes are small. The ncn_status.py script does not modify the system. It only provides information while doing the NCN remove.

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-04 17:52 UTC, rsjostrand-hpe approved these changes

2022-05-05 00:19 UTC, mharding-hpe requested changes
Does this also need PRs for 1.2 and main?

2022-05-05 00:19 UTC, mharding-hpe commented on operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_Data.md
> +1. Shutdown cray-reds:
```suggestion
1. Shutdown `cray-reds`:
```

2022-05-05 00:19 UTC, mharding-hpe commented on operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_Data.md
> +    If workers have been removed and the worker count is currently at two, a time out restarting cray-bss can be ignored. For example, the following failure output from `remove_management_ncn.py` can
```suggestion
    If workers have been removed and the worker count is currently at two, a timeout restarting `cray-bss` can be ignored. For example, the following failure output from `remove_management_ncn.py` can be ignored.
```

2022-05-05 00:19 UTC, mharding-hpe commented on operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_Data.md
> +    ```screen
```suggestion
    ```text
```

2022-05-05 00:19 UTC, mharding-hpe commented on operations/node_management/Add_Remove_Replace_NCNs/Remove_NCN_Data.md
> +1. Start cray-reds:
```suggestion
1. Start `cray-reds`:
```

2022-05-06 21:43 UTC, shunr-hpe commented
> Does this also need PRs for 1.2 and main?

For 1.2 these changes are in the larger Add/Remove/Replace NCN PR:
https://github.com/Cray-HPE/docs-csm/pull/1536

2022-05-09 15:37 UTC, mharding-hpe approved these changes

2022-05-09 21:27 UTC, merged