CASMCMS-7993 Add procedure to customize iPXE binary names
Cray-HPE/docs-csm pull request #1542
Opened 2022-05-05 14:55 UTC by ecozzi-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

Add procedure to customize iPXE binary names

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMCMS-7993](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7993)

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-06 03:16 UTC, mharding-hpe requested changes

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +The default behavior for the cray-ipxe service is the build iPXE binaries with a well known name. However, to help
```suggestion
The default behavior for the cray-ipxe service is to build iPXE binaries with a well known name. However, to help
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +prevent untrusted access to the iPXE binaries, sites may manually customize the iPXE binary names to a site specific
```suggestion
prevent untrusted access to the iPXE binaries, sites may manually customize the iPXE binary names to a site-specific
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +    ncn-m001# kubectl get configmap -n services cray-ipxe-settings \
```suggestion
    ncn# kubectl get configmap -n services cray-ipxe-settings \
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +    -o yaml > /root/k8s/cray-ipxe-settings-backup.yaml
```suggestion
            -o yaml > /root/cray-ipxe-settings-backup.yaml
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +   | Regular iPXE | cray_ipxe_binary_name | ipxe.efi |
```suggestion
   | Regular iPXE | `cray_ipxe_binary_name` | `ipxe.efi` |
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +   | iPXE binary | Configmap Key Name | Default Value |
```suggestion
   | iPXE Binary | ConfigMap Key Name | Default Value |
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +   | Debug iPXE | cray_ipxe_debug_binary_name | debug-ipxe.efi |
```suggestion
   | Debug iPXE | `cray_ipxe_debug_binary_name` | `debug-ipxe.efi` |
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +   `cray-ipxe-settings` configmap. The cray-ipxe builder will automatically update these keys with the name of the currently built ipxe images once they are available.
```suggestion
   `cray-ipxe-settings` ConfigMap. The `cray-ipxe builder` will automatically update these keys with the name of the currently built iPXE images once they are available.
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +      ncn-m001#  kubectl edit configmap -n services cray-ipxe-settings
```suggestion
      ncn#  kubectl edit configmap -n services cray-ipxe-settings
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +           ncn-m001# kubectl get configmap -n services cray-ipxe-settings \
```suggestion
           ncn# kubectl get configmap -n services cray-ipxe-settings \
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +           -o yaml > /root/k8s/cray-ipxe-settings.yaml
```suggestion
                   -o yaml > /root/cray-ipxe-settings.yaml
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +        2. Edit the cray-ipxe-settings.yaml file.
```suggestion
        2. Edit the `cray-ipxe-settings.yaml` file.
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +           ncn-m001# vi /root/k8s/cray-ipxe-bss-ipxe.yaml
```suggestion
           ncn# vi /root/cray-ipxe-bss-ipxe.yaml
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +           ncn-m001# kubectl delete configmap -n services cray-ipxe-settings
```suggestion
           ncn# kubectl delete configmap -n services cray-ipxe-settings
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +           ncn-m001# kubectl create -f /root/k8s/cray-ipxe-settings.yaml
```suggestion
           ncn# kubectl create -f /root/cray-ipxe-settings.yaml
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +The cray-ipxe builder will detect the configuration change and rebuild the iPXE binaries within 30 to 90 seconds. Upon
```suggestion
The `cray-ipxe` builder will detect the configuration change and rebuild the iPXE binaries within 30 to 90 seconds. Upon
```

2022-05-06 03:16 UTC, mharding-hpe commented on operations/boot_orchestration/Customize_iPXE_Binary_Names.md
> +successfully building the newly named binaries, the cray-ipxe builder will delete the old binaries from the shared files
```suggestion
successfully building the newly named binaries, the `cray-ipxe` builder will delete the old binaries from the shared file
```

2022-05-06 17:30 UTC, mharding-hpe requested changes
Also, scroll to the bottom of the main PR page and see the markdown style and spelling linter checks. It scans any files being changed in the PR. Because Mikhail only recently added the linters, it will likely flag a lot of stuff in the files that wasn't being changed by your PR. However, the current goal is not to merge docs changes that run afoul of the linter, since otherwise we'd never get the old stuff cleaned up. 

Let me know if any of the linter complaints don't make sense to you and I can try to help out.

2022-05-06 21:05 UTC, mharding-hpe approved these changes
Looks good. Just need backport PRs to 1.2 and (if applicable) 1.0.

2022-05-09 19:26 UTC, mharding-hpe commented
/backport release/1.2

2022-05-09 19:31 UTC, mharding-hpe commented
Eric, I'll try to help you out and make the backport PR for this

2022-05-09 19:34 UTC, mharding-hpe requested changes

2022-05-09 19:34 UTC, mharding-hpe commented on operations/index.md
> +<<<<<<< HEAD
This should not be in there

2022-05-09 19:34 UTC, mharding-hpe commented on operations/index.md
> +- [Configuration Management](configuration_management/Configuration_Management.md)
This looks like duplicated content.

2022-05-09 19:38 UTC, mharding-hpe commented
I'm going to try to see if I can fix this up for you, Eric, since the problem is just with the index file, and I believe you just wanted to add an entry to that.,

2022-05-09 20:17 UTC, ecozzi-hpe commented on operations/index.md
> +- [Configuration Management](configuration_management/Configuration_Management.md)
Done

2022-05-10 13:43 UTC, ecozzi-hpe commented
The master branch has been updated for spelling and style changes that now conflict with the changes I have made in this PR. I'm going to close this PR and try again with a fresh PR.

2022-05-10 13:43 UTC, closed without merging