CASMPET-5478 main : Update docs and Test Add/Remove/Replace NCN on 1.2
Cray-HPE/docs-csm pull request #1569
Opened 2022-05-06 20:05 UTC by kimjensen-hpe

## Summary and Scope
1.2 docs and scripts for Add/Remove/Replace/Move NCN

Covers all the issues found during testing of the procedure on a 1.2.0 beta system, including
* CASMNET-1514 ./ncn_add_pre-req.py - add some data handing
* CASMNET-1386 Kea/SMD race condition
* CASMHMS-5521 HSM/REDS race condition on remove

Resolves the following EPIC tickets
* CASM-2769 : Document and test procedures to add/remove/replace an NCN master and worker node
* CASM-2772 : Document and test procedures to add, remove, and replace an NCN storage node
* CASM-2787 : HMS support of the NCN Replace/Remove/Add Procedures

CASM-2786 : NET support of the NCN Replace/Remove/Add Procedures **still needs to address CASMNET-1530 for Add/Remove Switch Config**

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMPET-5478](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5478)
* Change will also be needed release/1.2
* Future work required by 
[CASMNET-1530](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1530) for Add/Remove Switch Config
[CASMPET-5571](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5571) Additional release/1.0 changes needed for Add/Remove/Replace
* Documentation changes required in NA
* Merge with/before/after NA

## Testing

fanta

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

Tested Add/Remove/Replace/Move of masters, workers and storage nodes on fanta (1.2.0 beta 104)
Did not cover 
* ncn_add_pre-req.py since fanta was fresh installed with added NCNs, no network adjustment was needed; this was tested in the 1.0.
* add/remove switch config (CASMNET-1530 TBD)

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

We will want to white glove the first customer to use this for 1.2 given the switch config changes have not been documented/tested yet and the network adjustment script (ncn_add_pre-req.py) could use some additional 1.2 testing.

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [x] Target branch correct
- [ ] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-06 20:18 UTC, rsjostrand-hpe approved these changes

2022-05-06 20:18 UTC, dzou-hpe approved these changes

2022-05-06 20:24 UTC, bklei approved these changes

2022-05-06 21:08 UTC, mharding-hpe requested changes
The same changes requested for the other PR apply here:
https://github.com/Cray-HPE/docs-csm/pull/1536

2022-05-09 22:57 UTC, kimjensen-hpe commented
> The same changes requested for the other PR apply here: #1536

Done

2022-05-10 18:18 UTC, mharding-hpe approved these changes

2022-05-10 20:50 UTC, merged