Casmmon 138 r1.0
Cray-HPE/docs-csm pull request #1600
Opened 2022-05-10 23:41 UTC by mantoanibroadwing

Updating https://github.com/Cray-HPE/docs-csm/blob/release/1.0/operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md

2022-05-11 01:57 UTC, mharding-hpe requested changes

2022-05-11 01:57 UTC, mharding-hpe commented on operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
> +4. Verify if service/cray-bos-etcd-client was created.
```suggestion
4. Verify that the `cray-bos-etcd-client` service was created.
```

2022-05-11 01:57 UTC, mharding-hpe commented on operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
> +       $ kubectl get service -A | grep cray-bos-etcd-client
```suggestion
       ncn# kubectl get service -n services cray-bos-etcd-client
```

2022-05-11 01:57 UTC, mharding-hpe commented on operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
> +       $
````suggestion
       ```

       Example of output showing that the service was created:    

       ```text
       NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
       cray-bos-etcd-client   ClusterIP   10.28.248.232   <none>        2379/TCP   2m
````

2022-05-11 01:57 UTC, mharding-hpe commented on operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
> +      1. If service was not created repeat steps 1 to 3 for a new backup restore.
```suggestion
      If the service was not created, then repeat the procedure for a new backup restore.
```

2022-05-11 01:57 UTC, mharding-hpe commented on operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
>      Replace etcd.backup\_v277935\_2020-03-30-23:52:54 in the command below with the name of the backup being used.
```suggestion
    Replace `etcd.backup_v277935_2020-03-30-23:52:54` in the command below with the name of the backup being used.
```

2022-05-11 13:32 UTC, johren-hpe commented
I wonder why only two checks out of the 6 have run here.

2022-05-11 15:34 UTC, mharding-hpe commented
> I wonder why only two checks out of the 6 have run here.

Good question. @mtupitsyn any idea?

2022-05-12 20:48 UTC, mharding-hpe commented
I rebased this and force pushed up the changes -- I want to see if it runs all of the checks this time.

2022-06-06 17:13 UTC, kimjensen-hpe requested changes
A PR for release/1.2 and main is also needed.

2022-06-06 17:13 UTC, kimjensen-hpe commented on operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
> +      If the service was not created, then repeat the procedure for a new backup restore.
```suggestion
      If the `etcd-client` service was not created, then repeat the procedure to restore the cluster again.
```

2022-06-07 18:08 UTC, mharding-hpe commented
Since @mantoanibroadwing hadn't touch this one in a while, I went ahead and fixed the linter complaints.

2022-06-07 18:09 UTC, mharding-hpe commented
It will still need the backports that Kim mentioned above

2022-06-07 18:09 UTC, mharding-hpe approved these changes

2022-06-07 18:10 UTC, mharding-hpe commented on operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
> +    ncn-w001# kubectl -n services get pod | grep SERVICE_NAME
```suggestion
    ncn# kubectl -n services get pod | grep SERVICE_NAME
```

2022-06-07 18:10 UTC, mharding-hpe commented on operations/kubernetes/Restore_an_etcd_Cluster_from_a_Backup.md
> +    ncn-w001# kubectl -n services delete etcdrestore.etcd.database.coreos.com/cray-bos-etcd
```suggestion
    ncn# kubectl -n services delete etcdrestore.etcd.database.coreos.com/cray-bos-etcd
```

2022-06-07 18:11 UTC, mharding-hpe approved these changes

2022-06-07 18:11 UTC, mharding-hpe commented
/backport release/1.2 main

2022-06-07 18:12 UTC, mharding-hpe commented
Looks like the backports will require manual intervention

2022-06-22 19:18 UTC, rustydb approved these changes

2022-07-04 18:49 UTC, mantoanibroadwing commented
> A PR for release/1.2 and main is also needed.

Will create it for sure

2022-07-11 19:15 UTC, rustydb commented
@kimjensen-hpe is on vacation, otherwise we just need her stamp/re-review. We also need the backports created @mantoanibroadwing .

2022-09-15 22:58 UTC, kimjensen-hpe approved these changes
This looks fine for csm1.0, though we should also backport this for 1.2 and 1.3 as it's still relevant

2022-09-16 19:20 UTC, merged

2022-09-16 19:20 UTC, rustydb commented
/backport release/1.2 release/1.3 main