Add note about SMS test failure after etcd restore
Cray-HPE/docs-csm pull request #1609
Opened 2022-05-11 19:31 UTC by bklei

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

* Resolves [CASMINST-4611](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4611)

## Testing

N/A

### Tested on:

N/A

### Test description:

N/A

## Risks and Mitigations

Low

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-11 19:49 UTC, mharding-hpe requested changes

2022-05-11 19:49 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +If an Etcd restore has been performed on one of the `SMS` services (such as `BOS` or `CRUS`), the first Etcd pod that comes up after the restore will not have a `PVC` (Persistent Volume Claim) attach
```suggestion
If an Etcd restore has been performed on one of the `SMS` services (such as `BOS` or `CRUS`), the first Etcd pod that comes up after the restore will not have a `PVC` (Persistent Volume Claim)
attached to it (until the pod is restarted). The Etcd cluster is in a healthy state at this point, but the SMS Health Checks will detect the absence of the PVC and may report errors similar to:
```

2022-05-11 19:49 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +In this case, these errors can be ignored, or the pod with the same name as the `PVC` mentioned in the output can be restarted (as long as the other twe Etcd pods are healthy).
```suggestion
In this case, these errors can be ignored, or the pod with the same name as the `PVC` mentioned in the output can be restarted (as long as the other two Etcd pods are healthy).
```

2022-05-11 20:09 UTC, bklei commented on operations/validate_csm_health.md
> +If an Etcd restore has been performed on one of the `SMS` services (such as `BOS` or `CRUS`), the first Etcd pod that comes up after the restore will not have a `PVC` (Persistent Volume Claim) attach
will break the line

2022-05-11 20:22 UTC, cdelatte-hpe approved these changes

2022-05-11 20:52 UTC, bklei commented on operations/validate_csm_health.md
> +In this case, these errors can be ignored, or the pod with the same name as the `PVC` mentioned in the output can be restarted (as long as the other twe Etcd pods are healthy).
good catch -- fixing

2022-05-11 22:04 UTC, kburns-hpe approved these changes

2022-05-11 23:11 UTC, rgross727 approved these changes

2022-05-12 19:19 UTC, mharding-hpe approved these changes

2022-05-12 19:42 UTC, merged