CASMPET-5593 Fix problematic commands
Cray-HPE/docs-csm pull request #1633
Opened 2022-05-16 16:18 UTC by kburns-hpe

This fixes some issues where spacing would cause the command to try to run rm / if you copy/pasted it. It also replaces the sysmgmt hand-edits with a for loop that will reduce errors and prevent the sysmgmt.yaml that's saved in the loftsman namespace from being overwritten. Commands were tested on Loki.

2022-05-16 16:37 UTC, bklei approved these changes

2022-05-16 16:51 UTC, rgross727 approved these changes

2022-05-17 19:40 UTC, mharding-hpe requested changes

2022-05-17 19:40 UTC, mharding-hpe commented on operations/spire/Restore_Spire_Postgres_without_a_Backup.md
> +3. Disable spire-agent on all of the Kubernetes NCNs (all worker nodes and
```suggestion
3. Disable `spire-agent` on all of the Kubernetes NCNs (all worker nodes and
```

2022-05-17 19:40 UTC, mharding-hpe commented on operations/spire/Restore_Spire_Postgres_without_a_Backup.md
> +
```suggestion
```

2022-05-17 19:40 UTC, mharding-hpe commented on operations/spire/Restore_Spire_Postgres_without_a_Backup.md
> +   `https://packages.local/repository/charts`
```suggestion
   `https://packages.local/repository/charts`.
```

2022-05-17 19:46 UTC, mharding-hpe approved these changes

2022-05-23 19:44 UTC, merged