CASMPET-5640 Corrected VCS Password Update instructions
Cray-HPE/docs-csm pull request #1657
Opened 2022-05-18 23:02 UTC by atifsyedali

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

Corrected VCS password update instructions. No code changes.

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

VCS password update instructions have stayed the same since 1.0 to mainline dev so not expecting incompatibilities.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMPET-5640](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5640)
* Change will also be needed in `release/1.2` and `main`
* ~Future work required by [issue id](issue link)~
* ~Documentation changes required in [issue id](issue link)~
* ~Merge with/before/after `<insert PR URL here>`~

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `fanta`

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

1. Followed instructions to change VCS password and then verified the change by logging into VCS.
2. Change the VCS password back.

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No
- Were continuous integration tests run? If not, why?  No
- Was upgrade tested? If not, why?  No
- Was downgrade tested? If not, why?  No
- Were new tests (or test issues/Jiras) created for this change?  No

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

No other known issues.

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-19 15:25 UTC, nrockershousen requested changes

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +    ```bash
Indent this code block under the above bullet

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +    ```bash
Indent this code block under the above bullet

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +    ```bash
Indent this code block under the above bullet

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +   Point a browser at `https://auth.SYSTEM_DOMAIN_NAME/keycloak/admin`, replacing SYSTEM\_DOMAIN\_NAME with the actual NCN's DNS name.
```suggestion
   Point a browser at `https://auth.SYSTEM_DOMAIN_NAME/keycloak/admin`, replacing `SYSTEM_DOMAIN_NAME` with the actual NCN's DNS name.
```
```suggestion
   Point a browser at `https://auth.SYSTEM_DOMAIN_NAME/keycloak/admin`, replacing SYSTEM\_DOMAIN\_NAME with the actual NCN's DNS name.
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +   Point a browser at `https://auth.SYSTEM_DOMAIN_NAME/keycloak/admin`, replacing SYSTEM\_DOMAIN\_NAME with the actual NCN's DNS name.
```suggestion
   Point a browser at `https://auth.SYSTEM_DOMAIN_NAME/keycloak/admin`, replacing `SYSTEM_DOMAIN_NAME` with the actual NCN's DNS name.
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +   The following is an example URL for a system: 'https://auth.cmn.system1.us.cray.com/keycloak/admin`
```suggestion
   The following is an example URL for a system: `https://auth.cmn.system1.us.cray.com/keycloak/admin`
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +   The following is an example URL for a system: 'https://auth.cmn.system1.us.cray.com/keycloak/admin`
```suggestion
   The following is an example URL for a system: `https://auth.cmn.system1.us.cray.com/keycloak/admin`
```
```suggestion
   The following is an example URL for a system: 'https://auth.cmn.system1.us.cray.com/keycloak/admin`
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +1. Now log in to Gitea with the default admin credentials.
```suggestion
1. Log in to Gitea with the default `admin` credentials.
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +1. Now log in to Gitea with the default admin credentials.
```suggestion
1. Log in to Gitea with the default `admin` credentials.
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +   Use the following admin login credentials:
```suggestion
   Use the following `admin` login credentials:
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +   Use the following admin login credentials:
```suggestion
   Use the following `admin` login credentials:
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +1. Enter the existing password (from previous step), new password and confirmation, and then click `Update Password`.
```suggestion
1. Enter the existing password (from previous step), new password, and confirmation, and then click `Update Password`.
```
```suggestion
1. Enter the existing password (from previous step), new password and confirmation, and then click `Update Password`.
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +1. Enter the existing password (from previous step), new password and confirmation, and then click `Update Password`.
```suggestion
1. Enter the existing password (from previous step), new password, and confirmation, and then click `Update Password`.
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +1. Copy the directory `vendor/stash.us.cray.com/scm/shasta-cfg/stable/utils` to your desired working directory, and run the following commands from that working directory.
```suggestion
1. Copy the directory `vendor/stash.us.cray.com/scm/shasta-cfg/stable/utils` to the desired working directory.
1. Change directories to be in the working directory set in the previous step.
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +1. Copy the directory `vendor/stash.us.cray.com/scm/shasta-cfg/stable/utils` to your desired working directory, and run the following commands from that working directory.
```suggestion
1. Copy the directory `vendor/stash.us.cray.com/scm/shasta-cfg/stable/utils` to the desired working directory.
1. Change directories to be in the working directory set in the previous step.
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +   If the above command complains that it cannot find `certs/sealed_secrets.crt` then you can run the following commands to create it:
```suggestion
   If the above command complains that it cannot find `certs/sealed_secrets.crt`, then you can run the following commands to create it:
```
```suggestion
   If the above command complains that it cannot find `certs/sealed_secrets.crt` then you can run the following commands to create it:
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +   If the above command complains that it cannot find `certs/sealed_secrets.crt` then you can run the following commands to create it:
```suggestion
   If the above command complains that it cannot find `certs/sealed_secrets.crt`, then you can run the following commands to create it:
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +1. Log in to Keycloak with the default admin credentials.
```suggestion
1. Log in to Keycloak with the default `admin` credentials.
```

2022-05-19 15:25 UTC, nrockershousen commented on operations/configuration_management/Version_Control_Service_VCS.md
> +1. Log in to Keycloak with the default admin credentials.
```suggestion
1. Log in to Keycloak with the default `admin` credentials.
```

2022-05-19 17:31 UTC, atifsyedali commented
@nrockershousen Thanks for your review and suggestions!

2022-05-19 20:00 UTC, mharding-hpe requested changes
Same changes as this PR: https://github.com/Cray-HPE/docs-csm/pull/1661

2022-05-20 14:58 UTC, atifsyedali commented
> Same changes as this PR: #1661

Done

2022-05-20 19:53 UTC, mharding-hpe approved these changes

2022-05-20 20:39 UTC, nrockershousen approved these changes

2022-05-23 15:35 UTC, atifsyedali commented
I don't seem to have permissions to merge. Can someone please squash and merge this?

2022-05-26 15:07 UTC, atifsyedali commented on operations/configuration_management/Version_Control_Service_VCS.md
> +        name: sysmgmt
@kburns-hpe Made changes as you suggested. Can you please review? Thanks

2022-06-03 14:23 UTC, kburns-hpe commented on operations/configuration_management/Version_Control_Service_VCS.md
> +        name: sysmgmt
looks good.

2022-06-03 14:23 UTC, kburns-hpe approved these changes

2022-06-03 17:49 UTC, merged