CASMPET-5640 Corrected VCS Password Update instructions (release/1.2)
Cray-HPE/docs-csm pull request #1661
Opened 2022-05-19 18:07 UTC by atifsyedali

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

Corrected VCS password update instructions. No code changes.

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

VCS password update instructions have stayed the same since 1.0 to mainline dev so not expecting incompatibilities.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMPET-5640](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5640)
* Change will also be needed in `release/1.0` and `main`
* ~Future work required by [issue id](issue link)~
* ~Documentation changes required in [issue id](issue link)~
* ~Merge with/before/after `<insert PR URL here>`~

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `fanta`

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

1. Followed instructions to change VCS password and then verified the change by logging into VCS.
2. Change the VCS password back.

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No
- Were continuous integration tests run? If not, why?  No
- Was upgrade tested? If not, why?  No
- Was downgrade tested? If not, why?  No
- Were new tests (or test issues/Jiras) created for this change?  No

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

No other known issues.

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-19 19:59 UTC, mharding-hpe requested changes

2022-05-19 19:59 UTC, mharding-hpe commented on operations/configuration_management/Version_Control_Service_VCS.md
>  ## Access the `cray` Gitea Organization
```suggestion
## Access the `cray` Gitea organization
```

2022-05-19 19:59 UTC, mharding-hpe commented on operations/configuration_management/Version_Control_Service_VCS.md
>  ## Backup and Restore Data
```suggestion
## Backup and restore data
```

2022-05-19 19:59 UTC, mharding-hpe commented on operations/configuration_management/Version_Control_Service_VCS.md
>  ### Backup Postgres Data
```suggestion
### Backup Postgres data
```

2022-05-19 19:59 UTC, mharding-hpe commented on operations/configuration_management/Version_Control_Service_VCS.md
>  ### Backup PVC Data
```suggestion
### Backup PVC data
```

2022-05-19 19:59 UTC, mharding-hpe commented on operations/configuration_management/Version_Control_Service_VCS.md
>  ### Restore Postgres Data
```suggestion
### Restore Postgres data
```

2022-05-19 19:59 UTC, mharding-hpe commented on operations/configuration_management/Version_Control_Service_VCS.md
>  ### Restore PVC Data
```suggestion
### Restore PVC data
```

2022-05-19 19:59 UTC, mharding-hpe commented on operations/configuration_management/Version_Control_Service_VCS.md
>  ### Alternative Backup/Restore Strategy
```suggestion
### Alternative backup/restore strategy
```

2022-05-20 14:57 UTC, atifsyedali commented
Thanks for the review @mharding-hpe!

2022-05-20 19:52 UTC, mharding-hpe approved these changes

2022-05-20 20:38 UTC, nrockershousen approved these changes

2022-05-23 15:35 UTC, atifsyedali commented
I don't seem to have permissions to merge. Can someone please squash and merge this?

2022-05-25 18:44 UTC, atifsyedali commented on operations/configuration_management/Version_Control_Service_VCS.md
> +        name: sysmgmt
@kburns-hpe Made changes as you suggested. Can you please review? Thanks

2022-06-01 17:57 UTC, atifsyedali commented on operations/configuration_management/Version_Control_Service_VCS.md
> +        name: sysmgmt
Hi @kburns-hpe Any chance you can have a look/approve at the changes today? Thanks.

2022-06-03 14:23 UTC, kburns-hpe approved these changes

2022-06-03 17:49 UTC, merged