MTL-1748 Update PoR to Align with NCN Behavior
Cray-HPE/docs-csm pull request #1665
Opened 2022-05-19 23:14 UTC by rustydb

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

The NCN behavior is a little less explicit and allows some freedom in the selection of OS disks.

Additionally NVME is fundamentally supported with the MTL-1748 changes.

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

Yes.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [MTL-1747](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1747)
* Change will also be needed in `release/1.2`

2022-05-20 16:13 UTC, jacobsalmela approved these changes

2022-05-20 19:29 UTC, mharding-hpe requested changes

2022-05-20 19:29 UTC, mharding-hpe commented on background/ncn_mounts_and_file_systems.md
>  ### Topics:
```suggestion
## Topics
```

2022-05-20 19:29 UTC, mharding-hpe commented on background/ncn_mounts_and_file_systems.md
>  The above table's rows with overlayFS map their "Mount Paths" to the "Upper Directory" in the table below:
```suggestion
The above table's rows with `overlayFS` map their `Mount Paths` to the `Upper Directory` in the table below:
```

2022-05-20 19:29 UTC, mharding-hpe commented on background/ncn_plan_of_record.md
> +Any of the disks may be used over the following busses:
My understanding is that both "busses" and "buses" are technically correct, but that "buses" is considered the more standard spelling.

```suggestion
Any of the disks may be used over the following buses:
```

2022-05-20 19:29 UTC, mharding-hpe commented on background/ncn_plan_of_record.md
> +> **`NOTE:`** USB is implicitly excluded during disk selection and wiping, the NCN's depoyment code will wipe all disks if they are a RAID or in the above list. The manual wipes will exclude USB, but
```suggestion
> **NOTE:** USB is implicitly excluded during disk selection and wiping. The NCN's deployment code will wipe all disks if they are a RAID or in the above list.
> The manual wipes will exclude USB, but it is recommended to verify that the manual wipes are actually doing so.
```

2022-05-20 19:29 UTC, mharding-hpe commented on background/ncn_plan_of_record.md
> +The OS disks are chosen by selecting the first two disks from a list containing all the disks in order by smallest to largest.
```suggestion
The OS disks are chosen by selecting the smallest disks. Two disks are used for OS disks by default.
```

2022-05-23 00:51 UTC, mharding-hpe approved these changes

2022-05-23 00:51 UTC, mharding-hpe commented
Should this be backported to 1.2?

2022-05-24 00:42 UTC, merged