copy 1.2 upgrade to 1.3 and rename path to 1.3
Cray-HPE/docs-csm pull request #1666
Opened 2022-05-20 00:19 UTC by dzou-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-20 19:18 UTC, mharding-hpe requested changes
Also, I thought we had decided to stop naming the directory in upgrade after the release. I can see it making sense to maybe split it up into different directories for different patch versions (like 1.0.0, 1.0.1, 1.0.10, etc), but anyone doing an upgrade with these docs will be going to 1.3, so having the 1.3 directory doesn't seem good (especially since it forces us to do this renaming each release).

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/Stage_0_Prerequisites.md
> +   linux# ssh admin@1.3.3.4
```suggestion
   linux# ssh admin@1.2.3.4
```

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/Stage_0_Prerequisites.md
> +     [Management Network 1.2 (`1.3 Preconfig`) to 1.3](../../operations/network/management_network/1.0_to_1.3_upgrade.md).
Is that a valid link target?

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/Stage_0_Prerequisites.md
> +     [Management Network 1.2 (`1.3 Preconfig`) to 1.3](../../operations/network/management_network/1.0_to_1.3_upgrade.md).
Is there going to be a 1.3 Preconfig? I didn't think we were making the same big network changes moving to that release.

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/README.SLS_Upgrade.md
> +        ncn# ./sls_updater_csm_1.3.py --sls-input-file sls_input_file.json \
The actual script file is not being renamed with this PR, so this command won't exist

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/README.SLS_Upgrade.md
> +        ncn# ./sls_updater_csm_1.3.py --sls-input-file sls_input_file.json \
The actual script file is not being renamed with this PR, so this command won't exist

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/README.SLS_Upgrade.md
> +ncn# ./sls_updater_csm_1.3.py --help
The actual script file is not being renamed with this PR, so this command won't exist

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/README.SLS_Upgrade.md
> +New for CSM 1.3, the BICAN network `ExtraProperties` value of `SystemDefaultRoute` is used
That is not new for 1.3

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/README.SLS_Upgrade.md
> +Switch names change in CSM 1.3 and must be applied in the following order:
This is not a change for 1.3

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/README.SLS_Upgrade.md
> +For CSM 1.3, the API gateway will no longer listen on the HMNLB MetalLB address pool.
This is not a change for 1.3

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/csm_1_2_upgrade/__init__.py
> +"""Modifications to SLS to upgrade from CSM 1.0.x to CSM 1.3."""
I don't think you're allowed to upgrade from 1.0 to 1.3

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/csm_1_2_upgrade/sls_updates.py
> +"""Functions used to update SLS from CSM 1.0.x to CSM 1.3."""
I don't think you're allowed to upgrade from 1.0 to 1.3

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/csm_1_2_upgrade/sls_updates.py
> +    """Rename CSM <=1.0.x switches to new CSM 1.3 naming.
This shouldn't be something we'd do for a 1.3 upgrade

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/csm_1_2_upgrade/sls_updates.py
> +    CSM 1.3 changes switch names in the following order:
This is not new for 1.3

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/csm_1_2_upgrade/sls_updates.py
> +    # The BICAN network only exists in CSM >=1.3.  If it exists do NOT migrate
```suggestion
    # The BICAN network only exists in CSM >=1.2.  If it exists do NOT migrate
```

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/expert_mode.md
> +ncn# ./sls_updater_csm_1.3.py \
Script needs to be renamed if this doc is using the new name

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/expert_mode.md
> +ncn# ./sls_updater_csm_1.3.py \
Script needs to be renamed if this doc is using the new name

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/expert_mode.md
> +ncn# ./sls_updater_csm_1.3.py \
Script needs to be renamed if this doc is using the new name

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/expert_mode.md
> +ncn# ./sls_updater_csm_1.3.py \
Script not renamed to match doc change

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/expert_mode.md
> +ncn# ./sls_updater_csm_1.3.py --sls-input-file sls_input_file.json --bican-user-network-name CAN \
Script not renamed to match doc change

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/expert_mode.md
> +2. Make an educated guess about how `sls_updater_csm_1.3.py` should work and run the program. A typical first pass is to `--preserve-existing-subnet-for-cmn external-dns`.
Script not renamed to match doc change

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/expert_mode.md
> +1. Review of the existing SLS file for CAN shows that NCN addresses are in the range: `10.103.11.3` to `10.103.11.14` with a DHCP Pool above this.
```suggestion
1. Review of the existing SLS file for CAN shows that NCN addresses are in the range: `10.103.11.2` to `10.103.11.14` with a DHCP Pool above this.
```

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/expert_mode.md
> +    ncn# ./sls_updater_csm_1.3.py \
Script not renamed to match doc change

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/sls/expert_mode.md
> +    ncn# ./sls_updater_csm_1.3.py \
Script not renamed to match doc change

2022-05-20 19:18 UTC, mharding-hpe commented on upgrade/1.3/scripts/upgrade/prerequisites.sh
> +    # Gitea change in 1.3 from /data to /var/lib/gitea, see which version we're
This is not a change in 1.3

2022-05-26 13:18 UTC, dzou-hpe commented
closing this one and work on a new one after talking to @mharding-hpe

2022-05-26 13:28 UTC, closed without merging