CASMTRIAGE-3173 for release/1.2
Cray-HPE/docs-csm pull request #1668
Opened 2022-05-20 17:44 UTC by alexanderkingh

## Summary and Scope

Docs change for the operations/boot_orchestration/Edit_the_iPXE_Embedded_Boot_Script.md and install/pxe_boot_troubleshooting.md. same as [PR #1552](https://github.com/Cray-HPE/docs-csm/pull/1552) but for reelase/1.2

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-20 19:02 UTC, mharding-hpe approved these changes

2022-05-20 19:05 UTC, mharding-hpe requested changes

2022-05-20 19:05 UTC, mharding-hpe commented on operations/boot_orchestration/Edit_the_iPXE_Embedded_Boot_Script.md
> +<<<<<<< HEAD
This should not be in there.

2022-05-24 19:47 UTC, denniswalker commented on operations/boot_orchestration/Edit_the_iPXE_Embedded_Boot_Script.md
> +<<<<<<< HEAD
Resolved

2022-05-24 19:48 UTC, merged

2022-05-24 19:49 UTC, denniswalker commented
/backport release/1.0 main

2022-05-25 19:13 UTC, mharding-hpe commented
This should be reverted.