CASMHMS-4664: Improvements from my experience fresh installing Hermod / CASMINST-4747 backport
Cray-HPE/docs-csm pull request #1677
Opened 2022-05-23 15:26 UTC by rsjostrand-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
CASMINST-4664: Improvements from my experience fresh installing Hermod
- All modified files were updated to appease the markdown linter.
- Collect MAC Addresses for NCNs:
   - Changed "Remove" to "Rename" in some steps to reflect the intent of the step better
   - Add an exit code check to grep checking for the placeholder MACs
- Collecting BMC MAC addresses
   - Use ipmitool locally to extract ncn-m001's BMC
- Collecting NCN MAC Addresses:
   - Add a step to power off NCNs after collecting MAC addresses
- Deploy management nodes
  - Add command example to power off NCNs after verifying node time
- Prepare Site-init
  - Add better descriptions for the BMC & SNMP credentails stored in customizations.yaml

Edit by Mitch:
I also pulled in my backports of https://github.com/Cray-HPE/docs-csm/pull/1744

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves CASMINST-4664

## Testing

_List the environments in which these changes were tested._

### Tested on:
   * Hermod

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
These new changes were tested on Hermod while performing a fresh install of CSM 1.2 RC2.

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_
Low risk

2022-05-23 18:28 UTC, nrockershousen commented on install/collecting_ncn_mac_addresses.md
> +`Bond0 MAC0` and `Bond0 MAC1` should be on the different network cards, in order to establish redundancy for a failed network card.
```suggestion
`Bond0 MAC0` and `Bond0 MAC1` should be on the different network cards in order to establish redundancy for a failed network card.
```

2022-05-23 18:28 UTC, nrockershousen commented on install/collecting_ncn_mac_addresses.md
> +    For each NCN update the corresponding row in `ncn_metadata` with the values for `Bond0 MAC0` and `Bond0 MAC1`. The `Bootstrap MAC` should have the same value as the `Bond0 MAC0`.
```suggestion
    For each NCN, update the corresponding row in `ncn_metadata` with the values for `Bond0 MAC0` and `Bond0 MAC1`. The `Bootstrap MAC` should have the same value as the `Bond0 MAC0`.
```

2022-05-23 18:28 UTC, nrockershousen commented on install/collecting_ncn_mac_addresses.md
> +1. Power off the NCNs
```suggestion
1. Power off the NCNs.
```

2022-05-26 15:33 UTC, mharding-hpe requested changes

2022-05-26 15:33 UTC, mharding-hpe commented on install/collect_mac_addresses_for_ncns.md
>     > **`WARNING`** Ensure that the `SYSTEM_NAME` environment variable is correctly set.
```suggestion
   > **WARNING** Ensure that the `SYSTEM_NAME` environment variable is correctly set.
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>      **`IMPORTANT`** The output of this command states that customizations.yaml should be reviewed and updated before
```suggestion
    **`IMPORTANT`** The output of this command states that `customizations.yaml` should be reviewed and updated before
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>      running the secrets-reencrypt.sh and secrets-seed-customizations.sh scripts. These two scripts will be run
```suggestion
    running the `secrets-reencrypt.sh` and `secrets-seed-customizations.sh` scripts. These two scripts will be run
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>      later in this document, do not run them at this time.
```suggestion
    later in this document; do not run them at this time.
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
> +    > NOTE: For `vault_redfish_defaults`, the only entry used is '{"Cray": {"Username": "root", "Password": "XXXX"}'
```suggestion
    > NOTE: For `vault_redfish_defaults`, the only entry used is `'{"Cray": {"Username": "root", "Password": "XXXX"}'`
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>      Validate MEDS credentials (used by the MEDS service, targeting Redfish BMC endpoints). Make sure Username and Password entries are correct.
```suggestion
    Validate MEDS credentials (used by the MEDS service, targeting Redfish BMC endpoints). Make sure `Username` and `Password` entries are correct.
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>      Validate RTS credentials (used by the Redfish Translation Service, targeting River Redfish BMC endpoints and PDU controllers). Make sure Username and Password entries are correct.
```suggestion
    Validate RTS credentials (used by the Redfish Translation Service, targeting River Redfish BMC endpoints and PDU controllers). Make sure `Username` and `Password` entries are correct.
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
> +1. To federate Keycloak with an upstream LDAP:
```suggestion
1. Federate Keycloak with an upstream LDAP server.
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>      1. Set environment variables for LDAP and PORT
```suggestion
    1. Set environment variables for `LDAP` and `PORT`.
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>         linux# export PORT=636
```suggestion
       linux# PORT=636
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>          This step builds an example that will create (or update) `cert.jks` with the PEM-encoded CA certificate for an LDAP host and then prepares `certs.jks.b64` which will be injected into customiz
```suggestion
        This step builds an example that will create (or update) `cert.jks` with the PEM-encoded CA certificate for an LDAP host and then prepares `certs.jks.b64` which will be injected into `customizations.yaml`.
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
> +1. (Optional) **`WARNING`** If production system or operational security is a
```suggestion
1. (Optional) **WARNING** If production system or operational security is a
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
> +Using `csi` on a generated `site-init` directory...
```suggestion
Using `csi` on a generated `site-init` directory:
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>  1. To assure it picks up the new meta-data:
```suggestion
1. Ensure that it picks up the new metadata:
```

2022-05-26 15:33 UTC, mharding-hpe commented on install/prepare_site_init.md
>  1. Unmount the shim from earlier if one was used.
```suggestion
1. Unmount the shim from earlier, if one was used.
```

2022-05-26 15:42 UTC, mharding-hpe requested changes
Sorry, missed a couple things on my first pass.

2022-05-31 22:31 UTC, mharding-hpe approved these changes

2022-06-02 16:53 UTC, rustydb approved these changes

2022-06-02 19:50 UTC, mharding-hpe commented
However, I see now that this badboy cannot automatically be rebased, so I will address that now.

2022-06-02 20:01 UTC, mharding-hpe commented
Rebased and squashed. All good and once again ready to merge.

2022-06-06 19:12 UTC, merged