STP-3180: Removing 1.5 specific heading in BOS topic
Cray-HPE/docs-csm pull request #1685
Opened 2022-05-24 18:07 UTC by nrockershousen

## Summary and Scope

Removing the 1.5 specific heading and doing some minor editing throughout the file.

## Issues and Related PRs

* Resolves [STP-3180](https://jira-pro.its.hpecorp.net:8443/browse/STP-3180)
* Merge with 

## Testing

N/A

### Tested on:

N/A

### Test description:

N/A

## Risks and Mitigations

None.

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-05-24 18:07 UTC, nrockershousen commented
/backport release/1.2

2022-05-24 19:15 UTC, mharding-hpe requested changes

2022-05-24 19:15 UTC, mharding-hpe commented on operations/boot_orchestration/Sessions.md
> +## Current BOS Session Limitations
```suggestion
## Current BOS session limitations
```

2022-05-25 13:38 UTC, nrockershousen commented on operations/boot_orchestration/Sessions.md
> +## BOA Functionality
Just a note on the style guide as our team has been discussing this recently. The Knowledge Management team (HPE version of Cray tech pubs) has a legacy HPE style guide and the Cray team has a legacy style guide intended for technical publications. The "HPE writing style guide" was created outside of HPE KM and Cray tech pubs. There are discrepancies between the three, and our team is trying to standardize some of the bigger consistency issues, such as headings. 

As long as we are being consistent within this publication this change is good. Just wanted to note this as there may be a different style in the future.

2022-05-25 13:48 UTC, nrockershousen commented on operations/boot_orchestration/Sessions.md
> +For example, if there is a 6,000 node system and 3 nodes fail to power off during a BOS operation.
This should stay as 3. If one number in a category of numbers requires a numeral, the other numbers should be numerals for consistency.

2022-05-25 18:53 UTC, mharding-hpe commented on operations/boot_orchestration/Sessions.md
> +For example, if there is a 6,000 node system and 3 nodes fail to power off during a BOS operation.
Good to know!

2022-05-25 18:55 UTC, mharding-hpe approved these changes

2022-06-06 20:17 UTC, jsollom-hpe approved these changes

2022-06-08 19:06 UTC, merged