CASMNET-1022-12
Cray-HPE/docs-csm pull request #1828
Opened 2022-06-13 17:08 UTC by atifsyedali

# Description

This introduces automated SSH access tests for the BiCAN test plan. Features:

1. Internal and external testing of SSH access
2. Customizable tests: choose which node types to test from, which node types to test to, and over which networks
3. Automatically selects nodes by querying SLS API and checking the status of each node through the HSM API
4. Framework for scripting and testing commands on multi-layered SSH connections.
5. Provisions to add more automated tests and tasks in the future, using existing utilities for APIs and SSH access
6. Docs on how to run these tests

# Checklist Before Merging

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/MTL-1695/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-06-13 18:42 UTC, mharding-hpe requested changes

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +By default, SSH access will be tested between nodes of type `ncn_master`, `cn`, `uan`, `spine_switch` on all relevant networks. You
```suggestion
By default, SSH access will be tested between master nodes , compute nodes, UANs, and spine switches. on all relevant networks.
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +can customize which nodes you want to test from and to, as well as the networks, by following the command line parameters as
```suggestion
It is possible to customize which nodes and networks will be tested. See the test usage statement for details.
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +described in the help:
```suggestion
The script usage statement is displayed by calling the test with the `--help` argument:
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +1. Install the python dependencies
```suggestion
1. Install the Python dependencies
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +   Switch to the `pyscripts` working directory and run the following command to install the required python dependencies:
```suggestion
   Run the following command from the `pyscripts` directory in order to install the required Python dependencies:
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +1. Obtain the admin client secret.
```suggestion
1. Obtain the `admin` client secret.
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +   Because we do not have access to `kubectl` outside of the cluster, obtain the admin client secret by running the
```suggestion
   Because `kubectl` will not work outside of the cluster, obtain the `admin` client secret by running the
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +    ncn# kubectl get secrets admin-client-auth -o jsonpath='{.data.client-secret}' | base64 -d
````suggestion
    ncn# kubectl get secrets admin-client-auth -o jsonpath='{.data.client-secret}' | base64 -d
    ```

    Example output:

    ```text
````

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +1. In the external system, execute the tests by running the following command:
```suggestion
1. On the external system, execute the tests.
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +1. The test will first ask you for the system domain. It will then ask for the admin client secret where you can enter the
```suggestion
1. When prompted by the test, enter the system domain and the `admin` client secret .
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +   secret that you obtained from the step above in the NCN. The tests will then run.
```suggestion
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +   By default, external SSH access will be tested to nodes of type `ncn_master`, `cn`, `uan`, `spine_switch` on all relevant networks. You
```suggestion
   By default, SSH access will be tested between master nodes , compute nodes, UANs, and spine switches. on all relevant networks.
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +   can customize which nodes you want to test, as well as the networks to test on, by following the command line parameters as
```suggestion
   It is possible to customize which nodes and networks will be tested. See the test usage statement for details.
```

2022-06-13 18:42 UTC, mharding-hpe commented on operations/validate_csm_health.md
> +   described in the help:
```suggestion
   The script usage statement is displayed by calling the test with the `--help` argument:
```

2022-06-13 18:45 UTC, mharding-hpe approved these changes

2022-06-13 19:23 UTC, rustydb approved these changes

2022-06-13 19:23 UTC, merged

2022-06-14 16:59 UTC, atifsyedali commented
Thanks guys for all the review and the fixes!