CASMINST-4818 Use New csm-releases Repository
Cray-HPE/docs-csm pull request #1851
Opened 2022-06-15 14:17 UTC by rustydb

This changes the URL from `releases` to `csm-releases`, where tarballs will now be published.

2022-06-15 14:50 UTC, heemstra approved these changes
Has linter problems... looks good otherwise.

2022-06-16 15:36 UTC, mharding-hpe requested changes
I am going to do some linting.

2022-06-16 15:36 UTC, mharding-hpe commented on install/pre-installation.md
> +   > **`NOTE`** `-C -` is used to allow partial downloads. These tarballs are considered large and
```suggestion
   > **NOTE** `-C -` is used to allow partial downloads. These tarballs are large;
```

2022-06-16 15:36 UTC, mharding-hpe commented on install/pre-installation.md
> +   > in the event of a connection disruption the same command can be used to continue where the
```suggestion
   > in the event of a connection disruption, the same command can be used to continue the
```

2022-06-16 15:36 UTC, mharding-hpe commented on install/pre-installation.md
>     > **`NOTE`** For users that are in an **air gap or behind a strict firewall**, the tarball will have to be obtained from the medium delivered by Cray-HPE. For these cases, please copy/download the
```suggestion
   > **NOTE** **If air-gapped or behind a strict firewall**, then the tarball must be obtained from the medium delivered by Cray-HPE. For these cases, copy/download the tarball to the working directory and then proceed to the next step. The tarball will need to be fetched with `scp` during the [download CSM tarball](#download-csm-tarball) step.
```

2022-06-16 15:37 UTC, mharding-hpe commented on .spelling
> + - install/pre-installation.md
```suggestion
- install/pre-installation.md
```

2022-06-16 17:13 UTC, mharding-hpe approved these changes

2022-06-16 19:41 UTC, rustydb commented
> Does this need to be changed as well or does this change not apply to 1.2?
> 
> https://github.com/Cray-HPE/docs-csm/blob/b6b8258da2a7c7fdedd5b4084ff2077b2fd9244a/upgrade/1.2/scripts/upgrade/prepare-assets.sh#L89

Fixed.

2022-06-16 19:44 UTC, rustydb commented
This might need backports to 1.0 and 1.2.

2022-06-16 19:46 UTC, phalseth-hpe approved these changes

2022-06-16 22:57 UTC, rustydb commented
I double checked and this addresses all the URLs in this branch. I'll get a backport for 1.2 up.

2022-06-17 19:12 UTC, merged