CASMPET-5646: Nexus Export and Restore Docs and Scripts
Cray-HPE/docs-csm pull request #2022
Opened 2022-07-11 21:39 UTC by ndavidson-hpe

# Description

This adds in a page in the Nexus documentation for a simple export and restore procedure. This procedure if used correctly will allow for an export of nexus to be taken before doing dangerous operations on nexus and allowing for a full safe restore of the nexus data.

# Checklist Before Merging

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-07-11 22:31 UTC, bklei approved these changes

2022-07-12 15:23 UTC, nrockershousen requested changes

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +A export is recommended to be done before an upgrade to enable the ability of rollback. Taking an export can also be used to improve Nexus resiliency by allowing easy fixes for data corruption.
```suggestion
An export is recommended to be done before an upgrade to enable the ability of rollback. Taking an export can also be used to improve Nexus resiliency by allowing easy fixes for data corruption.
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +Note about taking an export: There is only one export that should be taken, each time the script is run it will overwrite the old export.
```suggestion
**Note:** Only one export should be taken.  Each time the script is run, it will overwrite the old export.
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +Prior to making an export check the size of the exported tar file (on the cluster, e.g. 3 times size of just the export), and the amount of storage the cluster has left, run the following command on
```suggestion
Prior to making an export, check the size of the exported tar file on the cluster (for example, three times the size of just the export) and the amount of storage the cluster has left.

Run the following command on a master node (`ncn-m#`):
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +This command prints out the amount of space the Nexus export will take on the cluster. The command also prints the amount of space currently used in the Ceph pool that the export will be stored.
The above command will return the following information:

* The amount of space the Nexus export will take on the cluster.
* The amount of space currently used in the Ceph pool that the export will be stored.
* The max amount of space available in that Ceph pool.
   If the size of the Nexus export plus the size of the currently used space is larger than the max available size, submit a help request to figure out a solution.

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +1 hour for every 60 GiB stored in the nexus-data PVC. So for example if the nexus-data PVC is 120 GiB (meaning the first step showed the export will take 360 GiB on cluster)
```suggestion
1 hour for every 60 GiB stored in the nexus-data PVC. For example, if the nexus-data PVC is 120 GiB (meaning the first step showed the export will take 360 GiB on cluster)
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +To get an export run the export script on a master node:
```suggestion
To get an export, run the export script on a master node (`ncn-m#`):
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +The restore will delete any changes to made to Nexus after the backup was taken. The restore takes around half the time that the export took
```suggestion
The restore will delete any changes made to Nexus after the backup was taken. The restore takes around half the time that the export took
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +(e.g. if the export took 2 hours the restore would take around 1 hour) and during the time to restore Nexus is unavailable.
```suggestion
(for example, if the export took two hours the restore would take around one hour) and during the time to restore Nexus is unavailable.
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +To restore Nexus to the state of the backup run the restore script on any master node:
```suggestion
To restore Nexus to the state of the backup, run the restore script on any master node (`ncn-m#`):
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +If a new export is being created its recommended to first delete the old export to ensure everything exported correctly. If the old export is not deleted the new
```suggestion
If a new export is being created, it is recommended to first delete the old export to ensure everything exported correctly. If the old export is not deleted the new
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +To delete an export run:
```suggestion
To delete an export:
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +To clean up the job that the export created run:
```suggestion
To clean up the job that the export created:
```

2022-07-12 15:23 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +To clean up the job that the restore created run:
```suggestion
To clean up the job that the restore created:
```

2022-07-12 15:24 UTC, nrockershousen commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +This process is still a run at your own risk procedure, and is not recommended for all cases.
```suggestion
**CAUTION:** This process may be risky and is not recommended for all use cases.
```

2022-07-12 15:54 UTC, ndavidson-hpe commented on operations/package_repository_management/Nexus_Export_and_Restore.md
> +A export is recommended to be done before an upgrade to enable the ability of rollback. Taking an export can also be used to improve Nexus resiliency by allowing easy fixes for data corruption.
Fixed all suggestions in new commit.

2022-07-12 18:12 UTC, rustydb approved these changes

2022-07-12 19:17 UTC, mharding-hpe requested changes
Do not merge this yet -- I did some linting to the 1.2 PR, and also something else to it. Once the 1.2 PR is done, I'll need to pull those changes over here too.

2022-07-12 19:34 UTC, mharding-hpe approved these changes

2022-07-12 19:46 UTC, merged