Update HSM v1 API references to v2 CASMHMS-5541
Cray-HPE/docs-csm pull request #2036
Opened 2022-07-12 20:22 UTC by alvarez3-hpe

# Description

HSM's v1 API was deprecated and is being removed. This mod updates the HSM references to v2.

# Checklist Before Merging

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-07-13 18:53 UTC, rustydb approved these changes

2022-07-13 20:21 UTC, nrockershousen approved these changes

2022-07-14 16:23 UTC, mharding-hpe commented on operations/network/management_network/aruba/dhcp_decline.md
> +```bash
```suggestion
```text
```

2022-07-14 16:23 UTC, mharding-hpe commented on operations/network/management_network/mellanox/dhcp_decline.md
> +```bash
```suggestion
```text
```

2022-07-14 16:24 UTC, mharding-hpe commented on operations/network/management_network/mellanox/dhcp_decline.md
>  If you are seeing something similar too this in your logs;
```suggestion
If you are seeing something similar too this in the logs;
```

2022-07-14 16:26 UTC, mharding-hpe requested changes
I am doing some linting

2022-07-14 17:27 UTC, mharding-hpe approved these changes

2022-07-18 15:05 UTC, kosonenj approved these changes

2022-07-18 19:56 UTC, johren-hpe requested changes

2022-07-18 19:56 UTC, johren-hpe commented on operations/network/management_network/aruba/check_hsm.md
> +    curl -s -k -H "Authorization: Bearer ${TOKEN}" https://api_gw_service.local/apis/smd/hsm/v2/Inventory/EthernetInterfaces | jq
This should be api-gw-service-nmn.local instead of api_gw_service.local.

2022-07-18 19:56 UTC, johren-hpe commented on operations/network/management_network/aruba/check_hsm.md
> +    curl  -H "Authorization: Bearer ${TOKEN}" https://api_gw_service.local/apis/sls/v1/hardware | jq
This should be api-gw-service-nmn.local instead of api_gw_service.local.

2022-07-18 19:57 UTC, johren-hpe commented on operations/network/management_network/aruba/check_hsm.md
> +    curl -s -k -H "Authorization: Bearer ${TOKEN}" https://api_gw_service.local/apis/smd/hsm/v2/Inventory/EthernetInterfaces | jq
This should be api-gw-service-nmn.local instead of api_gw_service.local.

2022-07-18 19:59 UTC, johren-hpe commented on operations/network/management_network/mellanox/check_hsm.md
> +    curl -s -k -H "Authorization: Bearer ${TOKEN}" https://api_gw_service.local/apis/smd/hsm/v2/Inventory/EthernetInterfaces | jq
This should be api-gw-service-nmn.local instead of api_gw_service.local.

2022-07-18 19:59 UTC, johren-hpe commented on operations/network/management_network/mellanox/dhcp_decline.md
> +    curl -s -k -H "Authorization: Bearer ${TOKEN}" https://api_gw_service.local/apis/smd/hsm/v2/Inventory/EthernetInterfaces/18c04d13d73c
This should be api-gw-service-nmn.local instead of api_gw_service.local.

2022-07-19 19:13 UTC, merged