CASMPET-5786 1.3 : DOCS: Update postgres kubectl exec/logs calls to include postgres container
Cray-HPE/docs-csm pull request #2047
Opened 2022-07-13 18:32 UTC by kimjensen-hpe

# Description

Update docs to include postgres container as needed. 
Reviewed all the docs on the main branch and found a few places that also needed updates.
This is a follow on from CASMTRIAGE-3727

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-07-13 19:07 UTC, rustydb approved these changes

2022-07-13 19:08 UTC, mharding-hpe commented on operations/kubernetes/View_Postgres_Information_for_System_Databases.md
> +2. Log in as the `postgres` user.
```suggestion
1. Log in as the `postgres` user.
```

2022-07-13 19:08 UTC, mharding-hpe commented on operations/kubernetes/View_Postgres_Information_for_System_Databases.md
> +3. List the existing databases.
```suggestion
1. List the existing databases.
```

2022-07-13 19:09 UTC, mharding-hpe commented on operations/kubernetes/View_Postgres_Information_for_System_Databases.md
> +5. List the data types that are in the database being viewed.
```suggestion
1. List the data types that are in the database being viewed.
```

2022-07-13 19:10 UTC, mharding-hpe requested changes
Doing some linting

2022-07-13 19:49 UTC, mharding-hpe commented on operations/kubernetes/View_Postgres_Information_for_System_Databases.md
> +1. (`cray-smd-postgres#`) Log in as the `postgres` user.
```suggestion
1. (`postgres-container#`) Log in as the `postgres` user.
```

2022-07-14 01:42 UTC, rustydb approved these changes

2022-07-15 15:37 UTC, nrockershousen approved these changes

2022-07-15 19:21 UTC, merged