CASMINST-4942 put Stage_1 in argo
Cray-HPE/docs-csm pull request #2133
Opened 2022-07-27 17:01 UTC by leliasen-hpe

# Description

Put stage_1 into argo.

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-07-27 18:59 UTC, dzou-hpe requested changes
procedure doc is missing

2022-07-28 13:03 UTC, dzou-hpe approved these changes

2022-08-04 19:18 UTC, rustydb commented
@leliasen-hpe when I rebased and squashed this PR offline, it went well except for `storage.rebuild.yaml` which had lots of conflicts. That file is already in `main`, and I couldn't tell if yours or main's was "more right".

2022-08-04 20:28 UTC, dzou-hpe requested changes

2022-08-04 20:28 UTC, dzou-hpe commented on upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
> +    echo "--retry        Send RETRY request instead of CREATE if there is a failed worker rebuild/upgrade workflow already  (default: ${retry})"
@leliasen-hpe merge issue? we need to make retry default

2022-08-04 20:28 UTC, dzou-hpe commented on upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
> +            break;
another merge issue

2022-08-04 20:28 UTC, dzou-hpe commented on upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
> +            curl -sk -XPUT -H "Authorization: Bearer $(getToken)" "${baseUrl}/apis/nls/v1/workflows/${workflow}/retry"
here too

2022-08-04 20:28 UTC, dzou-hpe commented on upgrade/scripts/upgrade/ncn-upgrade-worker-storage-nodes.sh
> +        echo "  ${succeededSteps}"
same here

2022-08-05 10:45 UTC, GunashekarKM reviewed
Review completed for the updated MD file content.

2022-08-05 10:45 UTC, GunashekarKM commented on upgrade/Stage_1.md
> +   >> You can also upgrade multiple storage nodes with a comma separated list. This will upgrade the storage nodes sequentially.
```suggestion
   >> You can also upgrade multiple storage nodes with a comma-separated list. This upgrades the storage nodes sequentially.
```

2022-08-05 19:10 UTC, closed without merging