CASMNET-1744 canu install/upgrade procedure "main"
Cray-HPE/docs-csm pull request #2136
Opened 2022-07-27 19:31 UTC by kosonenj

# Description

upgrade/install canu

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-07-29 21:23 UTC, gbaker-hpe commented
@kosonenj We should update this PR with the language changes discussed on your other PR (https://github.com/Cray-HPE/docs-csm/pull/2135)

2022-08-01 19:05 UTC, rustydb requested changes
Needs spelling, links, and style checks remediation.

2022-08-03 19:07 UTC, rustydb approved these changes

2022-08-03 19:07 UTC, nrockershousen approved these changes

2022-08-03 19:07 UTC, merged