CASMINST-4963 CAN to CHN
Cray-HPE/docs-csm pull request #2237
Opened 2022-08-16 00:08 UTC by lukebates123

# Description

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-08-16 15:57 UTC, mharding-hpe commented on operations/network/management_network/bican_can_to_chn.md
> +   ncn-m001# export TOKEN=$(curl -s -k -S -d grant_type=client_credentials -d client_id=admin-client \
For 1.3+, the command prompts should not be inside the fenced block. In this case, you would change the earlier line to be:

```
1. (`ncn-m001#`) Obtain a token.

2022-08-16 15:57 UTC, mharding-hpe commented on operations/network/management_network/bican_can_to_chn.md
> +
Should add an intro here explaining what this page is documenting.

2022-08-17 21:57 UTC, lukebates123 commented on upgrade/scripts/sls/add_computes_to_chn.py
> -import ipaddress
Ran through black/flake8 with the CANU config file.

2022-08-17 23:19 UTC, trad511 requested changes

2022-08-17 23:19 UTC, trad511 commented on operations/network/management_network/bican_can_to_chn.md
> +The `CHN_VLAN` and `CHN_IPV4_SUBNET` should be discussed and agreed upon with the site networking team.
Take out the underscores.  Those are variables inside canu and we probably shouldn't ref those exactly.

Somewhere else we gave sizing guidance and should ref that here.
https://github.com/Cray-HPE/docs-csm/blob/7f913cee3ccafb1a88b1b26a62003514510a3ce0/operations/network/management_network/bican_support_matrix.md#can-or-chn-sizing-and-requirements
or correct branch.

2022-08-17 23:19 UTC, trad511 commented on operations/network/management_network/generate_switch_configs.md
>    * If doing a CSM install or upgrade, a CANU RPM is located in the release tarball. For more information, refer to the [Update CANU From CSM Tarball](canu/update_canu_from_csm_tarball.md) procedure.
probably overlap w/ Jouni's.  Check this shouldn't ref tarball directly, but the release.

2022-08-17 23:19 UTC, trad511 commented on operations/network/management_network/validate_shcd.md
> +# Validate the SHCD & Get JSON topology file
s/Get/Create

2022-08-17 23:19 UTC, trad511 commented on operations/network/management_network/validate_shcd.md
> +Once the validation is complete, a machine readable JSON file can be outputted.
s/can be outputted/should be produced/

2022-08-17 23:19 UTC, trad511 commented on upgrade/Stage_0_Prerequisites.md
> +   - If the banner does NOT contain text like the above, then contact support in order to get `CSM 1.3 switch configuration` applied to the system.
change to: "If the banner does NOT contain the appropriate CSM version, then apply the `CSM 1.3 switch configuration` or contact support.

2022-08-17 23:19 UTC, trad511 commented on upgrade/scripts/sls/sls_utils/Networks.py
> -    def system_default_route(self, default_route_network_name=None):
I don't think you should be changing anything in sls_utils unless something is totally broke.  It supports all the structures consistently.  Looks like you removed a function in the core lib to maintain the BICAN structure.

2022-08-22 15:59 UTC, kosonenj approved these changes

2022-08-23 15:19 UTC, mharding-hpe commented
I rebased, squashed the commits, and did minor linting.

2022-08-23 15:29 UTC, mharding-hpe approved these changes

2022-08-23 15:31 UTC, mharding-hpe commented
Probably should get @trad511 to re-review to make sure he's satisfied that his concerns were addressed.

2022-08-23 18:41 UTC, trad511 approved these changes

2022-08-23 19:16 UTC, merged