CASMUSER-3063: Add topic of repurposed compute nodes as UANs
Cray-HPE/docs-csm pull request #2243
Opened 2022-08-16 18:52 UTC by keopp-hpe

# Description

This PR adds a reference to the UAN docs for repurposing compute nodes as UANs.

# Checklist Before Merging

- [NA] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [NA] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-08-16 19:26 UTC, mharding-hpe requested changes

2022-08-16 19:26 UTC, mharding-hpe commented on operations/node_management/Repurpose_Compute_as_UAN.md
> +It is possible to repurpose a compute node to be used as a User Access Node (UAN).  This is typically done when the processor type of the compute node is not yet available in a UAN server.
```suggestion
It is possible to repurpose a compute node to be used as a User Access Node (UAN). This is typically done when the processor type of the compute node is not yet available in a UAN server.
```

2022-08-16 19:26 UTC, mharding-hpe commented on operations/node_management/Repurpose_Compute_as_UAN.md
> +Please see the ***Repurposing a Compute Node as a UAN*** section of the *HPE Cray User Access Node (UAN) Software Administration Guide (S-8033)* for further information.
```suggestion
See the **Repurposing a Compute Node as a UAN** section of the *HPE Cray User Access Node (UAN) Software Administration Guide (S-8033)* for further information.
```

2022-08-16 19:27 UTC, mharding-hpe commented
Does this need a 1.3 backport?

2022-08-16 19:47 UTC, keopp-hpe commented
@mharding-hpe , yes, this will need to be in 1.3 as the UAN docs supporting the repurposed compute nodes is in the UAN 2.5 which will go with 1.3.

2022-08-16 20:32 UTC, keopp-hpe commented
/backport release/1.3

2022-08-17 15:17 UTC, GunashekarKM commented on operations/node_management/Repurpose_Compute_as_UAN.md
> +See the **Repurposing a Compute Node as a UAN** section of the *HPE Cray User Access Node (UAN) Software Administration Guide (S-8033)* for further information.
```suggestion
For more information, see the **Repurposing a Compute Node as a UAN** section of the *HPE Cray User Access Node (UAN) Software Administration Guide (S-8033)*.
```

2022-08-17 19:01 UTC, mharding-hpe commented on operations/node_management/Repurpose_Compute_as_UAN.md
> +For more information, see the **Repurposing a Compute Node as a UAN** section of the *HPE Cray User Access Node (UAN) Software Administration Guide (S-8033)*.
```suggestion
For more information, see the **Repurposing a Compute Node as a UAN** section of the *HPE Cray User Access Node (UAN) Software Administration Guide (`S-8033`)*.
```

2022-08-17 19:03 UTC, mharding-hpe approved these changes

2022-08-17 19:11 UTC, rustydb approved these changes

2022-08-17 19:11 UTC, merged