CASMINST-5230 CASMINST-5229 LiveCD and CSI Path
Cray-HPE/docs-csm pull request #2244
Opened 2022-08-16 18:57 UTC by rustydb

# Description

This uses more specific `tar` and `bsdtar` arguments to get the LiveCD and PIT into a more reliable path.
    
The user is expected NOT to change directories between extracting the RPMs and using the USB path.

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I don't have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-08-16 19:24 UTC, mharding-hpe requested changes

2022-08-16 19:24 UTC, mharding-hpe commented on install/livecd/Boot_LiveCD_USB.md
> +        csi pit format "${USB}" ${OUT_DIR}/cray-pre-install-toolkit-*.iso 50000
```suggestion
        csi pit format "${USB}" "${OUT_DIR}/"cray-pre-install-toolkit-*.iso 50000
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/livecd/Boot_LiveCD_USB.md
> +        >    curl -f -o ${OUT_DIR}/write-livecd.sh https://raw.githubusercontent.com/Cray-HPE/cray-site-init/main/scripts/write-livecd.sh && chmod +x ${OUT_DIR}/write-livecd.sh
```suggestion
        >    curl -f -o "${OUT_DIR}/write-livecd.sh" https://raw.githubusercontent.com/Cray-HPE/cray-site-init/main/scripts/write-livecd.sh && chmod +x "${OUT_DIR}/write-livecd.sh"
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/livecd/Boot_LiveCD_USB.md
> +        >    bsdtar xvf cray-site-init-*.rpm --include *write-livecd.sh -C ./${OUT_DIR}
```suggestion
        >    bsdtar xvf cray-site-init-*.rpm --include *write-livecd.sh -C "./${OUT_DIR}"
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/livecd/Boot_LiveCD_USB.md
> +        >    mv -v ${OUT_DIR}/usr/local/bin/write-livecd.sh ./
```suggestion
        >    mv -v "${OUT_DIR}/usr/local/bin/write-livecd.sh" ./
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/livecd/Boot_LiveCD_USB.md
> +        >    rmdir -pv ${OUT_DIR}/usr/local/bin/
```suggestion
        >    rmdir -pv "${OUT_DIR}/usr/local/bin/"
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/livecd/Boot_LiveCD_USB.md
> +        write-livecd.sh "${USB}" ${OUT_DIR}/cray-pre-install-toolkit-*.iso 50000
```suggestion
        write-livecd.sh "${USB}" "${OUT_DIR}/"cray-pre-install-toolkit-*.iso 50000
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/pre-installation.md
> +   mkdir -pv ${OUT_DIR}
```suggestion
   mkdir -pv "${OUT_DIR}"
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/pre-installation.md
> +   tar -C ${OUT_DIR} --wildcards --no-anchored --transform='s/.*\///' -xzvf "csm-${CSM_RELEASE}.tar.gz" 'cray-pre-install-toolkit-*.iso'
```suggestion
   tar -C "${OUT_DIR}" --wildcards --no-anchored --transform='s/.*\///' -xzvf "csm-${CSM_RELEASE}.tar.gz" 'cray-pre-install-toolkit-*.iso'
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/pre-installation.md
> +         mkdir -pv ${OUT_DIR}
```suggestion
         mkdir -pv "${OUT_DIR}"
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/pre-installation.md
> +         tar -C ${OUT_DIR} --wildcards --no-anchored --transform='s/.*\///' -xzvf "csm-${CSM_RELEASE}.tar.gz" 'cray-site-init-*.rpm'
```suggestion
         tar -C "${OUT_DIR}" --wildcards --no-anchored --transform='s/.*\///' -xzvf "csm-${CSM_RELEASE}.tar.gz" 'cray-site-init-*.rpm'
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/pre-installation.md
> +            bsdtar xvf ${OUT_DIR}/cray-site-init-*.rpm --include *write-livecd.sh -C ${OUT_DIR}
```suggestion
            bsdtar xvf "${OUT_DIR}"/cray-site-init-*.rpm --include *write-livecd.sh -C "${OUT_DIR}"
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/pre-installation.md
> +            mv -v ${OUT_DIR}/usr/local/bin/write-livecd.sh ./${OUT_DIR}
```suggestion
            mv -v "${OUT_DIR}"/usr/local/bin/write-livecd.sh "./${OUT_DIR}"
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/pre-installation.md
> +            rmdir -pv ${OUT_DIR}/usr/local/bin/
```suggestion
            rmdir -pv "${OUT_DIR}/usr/local/bin/"
```

2022-08-16 19:24 UTC, mharding-hpe commented on install/pre-installation.md
> +            mv -v ./usr/local/bin/write-livecd.sh ./${OUT_DIR}
```suggestion
            mv -v ./usr/local/bin/write-livecd.sh "./${OUT_DIR}"
```

2022-08-17 19:11 UTC, mharding-hpe approved these changes

2022-08-17 19:12 UTC, rustydb commented
Will fix the spelling before making a backport.

2022-08-18 19:06 UTC, nrockershousen approved these changes

2022-08-18 19:07 UTC, merged

2022-08-18 19:07 UTC, rustydb commented
/backport main