CASMINST-5283 - Fix missing dir when moving the rbd device to another…
Cray-HPE/docs-csm pull request #2347
Opened 2022-08-26 19:42 UTC by cdelatte-hpe

… master node

# Description

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-08-26 21:10 UTC, mharding-hpe commented on scripts/csm_rbd_tool.py
> +
If this is commented, why not just remove the line?
```suggestion
```

2022-08-29 15:35 UTC, mharding-hpe requested changes

2022-08-29 15:35 UTC, mharding-hpe commented on scripts/csm_rbd_tool.py
> +
If this is commented, why not just remove the line?
```suggestion
```

2022-08-29 17:55 UTC, mharding-hpe approved these changes

2022-08-29 17:55 UTC, mharding-hpe commented
/backport main

2022-08-29 18:10 UTC, leliasen-hpe approved these changes

2022-08-29 18:34 UTC, bklei approved these changes

2022-08-29 18:59 UTC, cdelatte-hpe commented
/backport main

2022-08-29 19:01 UTC, cdelatte-hpe commented
/backport main

2022-08-29 19:12 UTC, cdelatte-hpe commented
/backport main

2022-08-29 19:14 UTC, cdelatte-hpe commented
/backport main

2022-08-29 19:17 UTC, rustydb approved these changes

2022-08-29 19:17 UTC, merged