CASMREL-1046 `kdump` overview and test plan
Cray-HPE/docs-csm pull request #2429
Opened 2022-09-07 18:52 UTC by rustydb

# Description

This provides a new section that describes `kdump`, its usage, and various test plans to use against it.

# Checklist Before Merging

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-09-07 19:00 UTC, jacobsalmela requested changes

2022-09-07 19:00 UTC, jacobsalmela commented on background/ncn_kdump.md
> +`kdump` is enabled when both the `kdump` package is installed *and* when the `crashkern` parameter is present on the command line.
`crashkernel`

2022-09-07 19:00 UTC, jacobsalmela commented on background/ncn_kdump.md
> +A dump can be analzyed using the `crash` command. The analysis requires `kernel-default-debuginfo`
perhaps a note that the versions must match

2022-09-07 19:21 UTC, jacobsalmela approved these changes

2022-09-07 19:22 UTC, rustydb commented
/backport main

2022-09-08 00:30 UTC, rustydb commented on background/ncn_kdump.md
> +* `$(lsblk -o MOUNTPOINT -nr /dev/disk/by-label/ROOTRAID)/boot` points to the actual `/boot` directory.
Meant to prepend an `ls`, I want to provide the literal paths for folks to check out. The path is kind of dynamic, albeit it rarely changes.

2022-09-08 00:32 UTC, rustydb commented on background/ncn_kdump.md
> +On metal artifacts, the `dracut-metal-mdsquash` module does some preparation for `kdump` by creating two symbolic links
Replacing with `squashFS`.

2022-09-08 00:32 UTC, rustydb commented on background/ncn_kdump.md
> +This usage sections denotes how the non-compute nodes configure and set `kdump` up.
This is how Minnesotan's speak.

2022-09-08 00:37 UTC, rustydb commented on background/ncn_kdump.md
> +> technically wrong for metal, but correct for Vagrant and Google Compute. The real root filesystem on metal is an overlayFS, but mounting the overlayFS
ur mom

2022-09-08 00:39 UTC, heemstra commented on background/ncn_kdump.md
> +* `$(lsblk -o MOUNTPOINT -nr /dev/disk/by-label/ROOTRAID)/boot` points to the actual `/boot` directory.
there's no closing paren

2022-09-08 00:40 UTC, heemstra commented on background/ncn_kdump.md
> +* `$(lsblk -o MOUNTPOINT -nr /dev/disk/by-label/ROOTRAID)/boot` points to the actual `/boot` directory.
oh. there is. not sure why I didn't see that the first time. but yeah, ls makes sense

2022-09-08 00:41 UTC, rustydb commented on background/ncn_kdump.md
> +> in `kdump` is complicated. To avoid complicating the `kdump` mount, `kdump` we provide `/` in the `/etc/fstab` file as `ROOTRAID`. The `ROOTRAID`
I think I've fixed this, please recheck.

2022-09-08 00:41 UTC, rustydb commented on background/ncn_kdump.md
> +in the root overlay.
Done.

2022-09-08 00:41 UTC, rustydb commented on background/ncn_kdump.md
> +This usage sections denotes how the non-compute nodes configure and set `kdump` up.
Fixed.

2022-09-08 00:41 UTC, rustydb commented on background/ncn_kdump.md
> +On metal artifacts, the `dracut-metal-mdsquash` module does some preparation for `kdump` by creating two symbolic links
Fixed.

2022-09-08 16:04 UTC, heemstra approved these changes

2022-09-09 19:27 UTC, merged