Casmnet 1875 main
Cray-HPE/docs-csm pull request #2467
Opened 2022-09-15 15:15 UTC by kosonenj

# Description

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-09-20 19:18 UTC, rustydb requested changes

2022-09-20 19:18 UTC, rustydb commented on troubleshooting/README.md
> +* [DHCP run book](dhcp_runbook.md)
Alpha-sort.
These DHCP and DNS books should probably go to lines 81/82.

2022-10-07 19:15 UTC, rustydb commented on troubleshooting/scripts/kea_unbound_check.sh
> +#!/usr/bin/env bash
```suggestion
#!/bin/bash
```

2022-10-07 19:15 UTC, rustydb approved these changes

2022-10-07 19:16 UTC, nrockershousen approved these changes

2022-10-07 20:20 UTC, merged