CASMCMS-8244: Update recommendations for image customization Ansible
Cray-HPE/docs-csm pull request #2527
Opened 2022-09-23 15:14 UTC by rbak-hpe

# Description

This updates the recommendations for writing Ansible targeting image customization.  This is slightly different than the recommendations for CASMCMS-8236, as 1.3 will not have a feature that we are recommending going forward.

# Checklist Before Merging

- [X] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [X] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

2022-09-23 16:31 UTC, jsollom-hpe requested changes

2022-09-23 16:31 UTC, jsollom-hpe commented on operations/configuration_management/Target_Ansible_Tasks_for_Image_Customization.md
> +## Using the a host group
Using a host group

2022-09-23 16:31 UTC, jsollom-hpe commented on operations/configuration_management/Target_Ansible_Tasks_for_Image_Customization.md
> +Ansible is most efficient at skipping tasks when the don't apply to any nodes in the current `hosts` target.  For this reason it's recommended that Ansible plays first setup a host group using the `a
Ansible is most efficient at skipping tasks when _they_ don't apply
Note: You forgot the 'y' in they.

and then use this _group_
Note: Add the word group

2022-09-23 16:31 UTC, jsollom-hpe commented on operations/configuration_management/Target_Ansible_Tasks_for_Image_Customization.md
> +    - name: Add image customization hosts to a the cfs_image host group.
Remove the unnecessary article 'a'.

2022-09-23 16:31 UTC, jsollom-hpe commented on operations/configuration_management/Target_Ansible_Tasks_for_Image_Customization.md
> +For ease of use, future versions of CFS will setup this group automatically during the inventory creation.  This won't significantly improve performance over using `add_host` task, but it will allow
Reworded and ordered:
For ease of use, future versions of CFS will set up this `cfs_image` group automatically during the inventory creation.  In preparation for this, create a `cfs_image` group _now_ to make that conversion simple in the future.  In CFS' next release, this `add_host` task can simply be removed without changing any other parts of the playbook.

2022-09-26 13:51 UTC, jsollom-hpe approved these changes

2022-09-26 19:18 UTC, rustydb approved these changes

2022-09-27 19:06 UTC, rustydb commented
[CASMINST-5382](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5382) strikes again, I haven't seen this issue hit `main` so I think the `CODEOWNERS` needs similar fixes in 1.3 like main received.

2022-09-27 19:35 UTC, merged