CASMINST-5329 doom lint
Cray-HPE/docs-csm pull request #2529
Opened 2022-09-23 15:30 UTC by rustydb

# Description

This incorporates some linting from my 1.2 install experience.

Namely it makes the painful site-init page easier to go through by using the newer page which is copy-paste friendly.

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-09-23 20:27 UTC, jacobsalmela requested changes
Github lint checks are failing, otherwise looks nice.

2022-09-23 20:49 UTC, jacobsalmela approved these changes

2022-09-26 11:57 UTC, spillerc-hpe requested changes

2022-09-26 11:57 UTC, spillerc-hpe commented on install/prepare_site_init.md
> +    "${SITE_INIT}/utils/secrets-seed-customizations.s"h "${SITE_INIT}/customizations.yaml"
Quote in wrong place `.s"h`

2022-09-26 12:06 UTC, spillerc-hpe approved these changes

2022-09-26 15:19 UTC, merged