CASMINST-5257: Add security hardening guide to CSM 1.3, insert into i…
Cray-HPE/docs-csm pull request #2550
Opened 2022-09-26 16:30 UTC by jeremy-duckworth

# Description

* Add security hardening guide for 1.3 release. Include in install and upgrade flows.
* Include xname-filtering, iPXE filename customization in hardening guide.
* Move Kubernetes API Encryption to security hardening guide (optional step). 

# Checklist Before Merging

- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

2022-09-26 16:30 UTC, jeremy-duckworth commented
+ @kburns-hpe this PR adds the setup for xname filtering into security hardening guide as optional procedure.

2022-09-26 16:31 UTC, jeremy-duckworth commented
@mitcharf  this PR moves Kubernetes API Encryption setup into the security hardening guide as an optional procedure.

2022-09-26 19:02 UTC, manderson-hpe commented on install/README.md
> +### 11. Apply Security Hardening
Should be `Apple security hardening` to match the rest of the document.

2022-09-26 19:09 UTC, rustydb requested changes

2022-09-26 19:09 UTC, rustydb commented on operations/CSM_product_management/Apply_Security_Hardening.md
> +    Perform procedure(s) in [Xname Validation](../spire/xname_validation.md).
nit: use lowercase "xname"

https://github.com/Cray-HPE/docs-csm/blob/main/.spelling#L621-L622

```suggestion
    Perform procedure(s) in [xname Validation](../spire/xname_validation.md).
```

2022-09-26 19:09 UTC, rustydb commented on operations/CSM_product_management/Apply_Security_Hardening.md
> +4. (Optional) Enable Spire and OPA Xname Validation.
nit: use lowercase "xname"

https://github.com/Cray-HPE/docs-csm/blob/main/.spelling#L621-L622

```suggestion
4. (Optional) Enable Spire and OPA xname Validation.
```

2022-09-26 19:11 UTC, manderson-hpe commented on upgrade/README.md
> +## 5. Apply Security Hardening
Should also be `Apply security hardening`.

2022-09-27 19:16 UTC, rustydb approved these changes

2022-09-27 19:23 UTC, heemstra approved these changes

2022-09-28 19:36 UTC, merged