Casmpet 5977 - csm_rbd_tool and cubs_tool documentation
Cray-HPE/docs-csm pull request #2576
Opened 2022-09-30 14:46 UTC by cdelatte-hpe

# Description

Usage docs for csm_rbd_tool and cubs_tool.

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-09-30 14:50 UTC, bklei approved these changes

2022-09-30 14:52 UTC, bo-quan approved these changes

2022-09-30 14:57 UTC, rgross727 approved these changes

2022-09-30 19:15 UTC, rustydb approved these changes

2022-10-03 16:36 UTC, leliasen-hpe commented
/backport main

2022-10-03 19:07 UTC, rustydb commented on operations/utility_storage/Cubs_tool_Usage.md
> +# Cubs_tool Usage
```suggestion
# `cubs_tool` Usage
```

2022-10-03 19:08 UTC, rustydb approved these changes

2022-10-03 19:08 UTC, rustydb commented on operations/utility_storage/Cubs_tool_Usage.md
> +Cubs_tool is a python script developed as a second tier Ceph upgrade watching tool.  This was to better integrate the Ceph upgrade process with the upgrade workflow tooling.
```suggestion
`cubs_tool` is a python script developed as a second tier Ceph upgrade watching tool.  This was to better integrate the Ceph upgrade process with the upgrade workflow tooling.
```

2022-10-03 19:08 UTC, rustydb commented on operations/utility_storage/Cubs_tool_Usage.md
> +* **in_family** - is referring to an upgrade staying within the same major version of Ceph.  E.g, Any upgrade within the same CSM release will contain the same Major version of Ceph, but could have m
```suggestion
* **`in_family`** - is referring to an upgrade staying within the same major version of Ceph.  E.g, Any upgrade within the same CSM release will contain the same Major version of Ceph, but could have minor version bumps or patched containers.
```

2022-10-03 19:08 UTC, rustydb commented on operations/utility_storage/Cubs_tool_Usage.md
> +***IMPORTANT:*** The cubs_tool.py utility at this time will only work on `ncn-s00[1-3]`.  Please ensure you are only attempting to run this tool from one of those servers.
```suggestion
***IMPORTANT:*** The `cubs_tool.py` utility at this time will only work on `ncn-s00[1-3]`.  Please ensure you are only attempting to run this tool from one of those servers.  
```

2022-10-03 19:14 UTC, rustydb approved these changes

2022-10-03 19:14 UTC, rustydb requested changes
Whitespace problems.

2022-10-03 19:15 UTC, nrockershousen submitted a review, later dismissed
Please add entries for the new files in the operations README file.

2022-10-03 19:54 UTC, denniswalker approved these changes

2022-10-03 19:55 UTC, rustydb approved these changes

2022-10-03 19:55 UTC, merged