STP-3226 (1.3): Procedure to enable audit logging
Cray-HPE/docs-csm pull request #2693
Opened 2022-10-20 14:05 UTC by nrockershousen

# Description

Manual 1.3 backport.

Moving the procedure to enable audit logging to the CSM docs. Resolves [STP-3226](https://jira-pro.its.hpecorp.net:8443/browse/STP-3226).

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-10-20 14:26 UTC, bo-quan approved these changes

2022-10-20 19:04 UTC, rustydb requested changes

2022-10-20 19:11 UTC, rustydb approved these changes

2022-10-20 20:01 UTC, mharding-hpe requested changes
The same issues apply here as in my 1.0 review (except that in some of those cases I was changing command prompts inside the code blocks, whereas here of course they should be changed in their new location)
https://github.com/Cray-HPE/docs-csm/pull/1642

2022-11-10 22:47 UTC, mharding-hpe approved these changes

2022-11-14 20:08 UTC, merged