Remove Redundant LiveCD Definition
Cray-HPE/docs-csm pull request #2724
Opened 2022-10-26 23:06 UTC by rustydb

# Description

Removes the redundant LiveCD definition, and adds emphasis to the PIT's aliases.

Signed-off-by: Russell Bunch <doomslayer@hpe.com>

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-10-26 23:06 UTC, rustydb commented
/backport release/1.3

2022-10-27 19:22 UTC, jacobsalmela requested changes

2022-10-27 19:22 UTC, jacobsalmela commented on glossary.md
> +The PIT is ephemeral, it runs in either in memory or it can be written to a USB stick for persistence.
...it runs in memory or it can...

2022-10-27 19:35 UTC, heemstra approved these changes

2022-10-27 19:36 UTC, jacobsalmela approved these changes

2022-10-27 20:07 UTC, merged