Changes from papaya shutdown test on shandy
Cray-HPE/docs-csm pull request #2821
Opened 2022-11-15 21:06 UTC by bklei

In progress -- don't review yet (or merge)

2022-11-15 21:18 UTC, cdelatte-hpe approved these changes

2022-11-19 04:22 UTC, rgross727 requested changes

2022-11-19 04:22 UTC, rgross727 commented on operations/power_management/Prepare_the_System_for_Power_Off.md
> +    scontrol update NodeName=scontrol update NodeName=nid[001001-001003,001005] State=DRAIN Reason="Shutdown" State=DRAIN Reason=<reason>
scontrol update NodeName=nid[001001-001003,001005] State=DRAIN Reason="Shutdown"
scontrol update NodeName=ALL State=DRAIN Reason="Shutdown"

2022-11-19 04:22 UTC, rgross727 commented on operations/power_management/System_Power_Off_Procedures.md
> +To power off standard rack and liquid-cooled cabinet PDUs, refer to [Power Off Compute Cabinets](Power_Off_Compute_Cabinets.md).
This link does not work. Maybe you need to delete the old file, Power_Off_Compute_and_IO_Cabinets.md
and have a new file named Power_Off_Compute_Cabinets.md?
Or maybe move it to its new name?

2022-11-19 04:31 UTC, rgross727 commented
In the Power_On_and_Start_the_Management_Kubernetes_Cluster.md document there are already several `cronjob`s which when rendered look different: "cronjob s" Not sure why?

2022-11-19 05:15 UTC, rgross727 commented on operations/README.md
> +- [Power Off Compute Cabinets](power_management/Power_Off_Compute_Cabinets.md)
This link does not work. Need to move the old file, Power_Off_Compute_and_IO_Cabinets.md
to its new name: Power_Off_Compute_Cabinets.md and edit the title in the moved file.

2022-11-21 18:13 UTC, rgross727 approved these changes

2022-11-21 18:15 UTC, kimjensen-hpe commented
/backport main

2022-11-21 19:22 UTC, bo-quan approved these changes

2022-11-21 20:33 UTC, rustydb approved these changes

2022-11-21 20:33 UTC, merged

2022-11-22 15:58 UTC, haasken-hpe commented on operations/power_management/Power_On_Compute_Cabinets.md
> +   Note that the default timeout for powering the compute cabinets is 60 seconds, which is generally too low.
@bklei, was this added due to CRAYSAT-1623? If so, it is not going to help with the timeout that occurs while waiting for the hms-discovery cronjob to be scheduled. I'm going to remove it when I rebase my PR #2841 on the latest main branch.