Add notice about UAIs if CHN is set but not installed and configured
Cray-HPE/docs-csm pull request #2824
Opened 2022-11-16 19:41 UTC by alanm-hpe

# Description

Document that UAIs will not be accessible if the CHN is set in SLS, but the CHN has not been installed and configured.
https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4499

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-11-16 20:23 UTC, rustydb requested changes

2022-11-16 20:23 UTC, rustydb commented on operations/validate_csm_health.md
> +   > **IMPORTANT:** If the site is configured to use the CHN, and the high speed network has not been
The style checker doesn't like this block quote being separate from the above block quote. I think you could merge them to fix the checker, or if you really want it to be separate maybe add another new line (assuming that doesn't make the style-checker fail again.

Using a list in the block quote would fix it (e.g. merging the above and new block quote into a single block quote that listed each item).

2022-11-17 20:14 UTC, rustydb approved these changes

2022-11-21 15:36 UTC, alanm-hpe commented
This is ready to merge. I would also like to target 1.3.1 for this change. Is `release/1.3` the correct branch?

2022-11-28 20:33 UTC, denniswalker approved these changes

2022-11-28 20:33 UTC, merged