Update Stage_1.md
Cray-HPE/docs-csm pull request #2832
Opened 2022-11-18 09:26 UTC by SavioJoshua

Signed-off-by: SavioJoshua <91620737+SavioJoshua@users.noreply.github.com>

# Description

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-11-18 19:53 UTC, rustydb approved these changes
I assume this is an adhoc fix, no JIRA?

2022-12-02 22:26 UTC, mharding-hpe approved these changes

2022-12-02 22:28 UTC, mharding-hpe requested changes

2022-12-02 22:28 UTC, mharding-hpe commented on upgrade/1.2/Stage_1.md
>  /usr/share/doc/csm/scripts/workarounds/boot-order/run.sh
This is to the 1.2 branch, so it should follow the prompt conventions for 1.2.

````suggestion
1. Apply a workaround for the boot order:

```bash
ncn-m001# /usr/share/doc/csm/scripts/workarounds/boot-order/run.sh
````

2022-12-02 22:30 UTC, mharding-hpe approved these changes

2022-12-02 22:30 UTC, mharding-hpe commented
This should merge, IMO.

2023-01-27 20:15 UTC, merged