CASMTRIAGE-4577 - DNS hangs seen on airgapped system when host lookups fail
Cray-HPE/docs-csm pull request #2848
Opened 2022-11-22 18:40 UTC by spillerc-hpe

# Description

Modify air-gapped DNS procedure to forward the `"."` zone to PowerDNS so queries don't hang and timeout and apply required workaround to `spire-postgres-pooler` to prevent spire database lookup failures.

# Checklist Before Merging

- [X] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-11-22 20:21 UTC, dle-hpe approved these changes

2022-11-23 20:22 UTC, rustydb approved these changes

2022-11-23 20:24 UTC, rustydb requested changes

2022-11-23 20:24 UTC, rustydb commented on troubleshooting/known_issues/spire_database_airgap_configuration.md
> +   containers:
Change to `yaml`.

2022-11-23 20:40 UTC, rustydb approved these changes

2022-11-23 20:40 UTC, merged