Update FAS procedures for component power off
Cray-HPE/docs-csm pull request #2885
Opened 2022-12-01 18:52 UTC by mjendrysik-hpe

# Description

Improve the documentation for component power off when doing a FAS firmware update.

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-12-02 22:22 UTC, mharding-hpe requested changes

2022-12-02 22:22 UTC, mharding-hpe commented on operations/firmware/FAS_Recipes.md
> +>       - If the chassis power is Off, everything else is Off, it is safe to proceed.
```suggestion
>   - Stop the `hms-discovery` job.
>
>     ```bash
>     ncn-mw# kubectl -n services patch cronjobs hms-discovery -p '{"spec":{"suspend":true}}'
>     ```
>
>   - Start the `hms-discovery` job.
>
>     ```bash
>     ncn-mw# kubectl -n services patch cronjobs hms-discovery -p '{"spec":{"suspend":false}}'
>     ```
>
> - Use CAPMC to make sure all chassis rectifier power is off.
>   1. Check power status of the chassis.
>
>     If the chassis power is off, then everything else is off, and it is safe to proceed.
>
>     ```bash
>     ncn-mw# cray capmc get_xname_status create --xnames x[1000-1008]c[0-7]
>     ```
>
>   1. If the chassis are still powered on, then use CAPMC to make sure everything is off.
>
>      1. Issue power off command.
>
>         > This command may produce a large list of errors when talking to BMCs. This is expected if the hardware
>         > has been partially powered down.
>
>         ```bash
>         ncn-mw# cray capmc xname_off create --xnames x[1000-1008]c[0-7] --force true --continue true --recursive true
>         ```
>
>      1. Verify that chassis power is off.
>
>         Repeat the earlier check of the chassis power.
```

2022-12-02 22:23 UTC, mharding-hpe commented on operations/firmware/FAS_Recipes.md
> +>         > has been partially powered down.
```suggestion
>         This command may produce a large list of errors when talking to BMCs. This is expected if the hardware
>         has been partially powered down.
```

2022-12-02 22:24 UTC, mharding-hpe approved these changes

2022-12-02 22:25 UTC, mharding-hpe commented
I believe this will need PRs for other branches as well. Is that right?

2022-12-06 20:18 UTC, rustydb commented
> I believe this will need PRs for other branches as well. Is that right?

It is:
- https://github.com/Cray-HPE/docs-csm/pull/2898
- https://github.com/Cray-HPE/docs-csm/pull/2899

2022-12-09 18:04 UTC, nieuwsma approved these changes

2022-12-12 20:10 UTC, merged