CASMHMS-5746 Update FAS procedures for component power off
Cray-HPE/docs-csm pull request #2898
Opened 2022-12-05 14:10 UTC by mjendrysik-hpe

# Description

Improve the documentation for component power off when doing a FAS firmware update.

# Checklist Before Merging

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-12-05 20:18 UTC, rustydb requested changes

2022-12-05 20:18 UTC, rustydb commented on operations/firmware/FAS_Recipes.md
> +>     ncn-mw# kubectl -n services patch cronjobs hms-discovery -p '{"spec":{"suspend":true}}'
Please make copy-paste friendly for release/1.3 and main.

https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#command-prompt-location

2022-12-14 22:10 UTC, rustydb approved these changes

2022-12-15 14:03 UTC, nrockershousen commented on operations/firmware/FAS_Recipes.md
> +> - The `hms-discovery` job must be stopped before updates are done and restarted after updates are complete.
```suggestion
> - Stop the `hms-discovery` job before updates are done, and then restart it after updates are complete.
```

2022-12-15 14:03 UTC, nrockershousen commented on operations/firmware/FAS_Recipes.md
> +>   - (`ncn-mw#`) Stop the `hms-discovery` job.
```suggestion
>   1. (`ncn-mw#`) Stop the `hms-discovery` job.
```

2022-12-15 14:03 UTC, nrockershousen commented on operations/firmware/FAS_Recipes.md
> +>   - (`ncn-mw#`) Start the `hms-discovery` job.
```suggestion
>   1. (`ncn-mw#`) Start the `hms-discovery` job.
```

2022-12-15 14:03 UTC, nrockershousen commented on operations/firmware/FAS_Recipes.md
> +>     ```
```suggestion
>      (`ncn-mw#`) If the chassis power is off, then everything else is off, and it is safe to proceed.
>
>      ```bash
>      cray capmc get_xname_status create --xnames x[1000-1008]c[0-7]
>      ```
```
indentation is off

2022-12-15 20:16 UTC, nrockershousen approved these changes

2022-12-15 20:16 UTC, merged