CASMCMS 8255
Cray-HPE/docs-csm pull request #2907
Opened 2022-12-05 22:35 UTC by jesseviola-hpe

# Description

Fixes from integration testing session.
1. New docker image fixing a file permission copy error, will now ignore and log unreadable files during upload.
2. Small path fix for volume mounting the vcs directory for upload
3. Changing the template name to match the stages.yaml
4. Remove redundant upload content template in the iuf dir

# Checklist Before Merging

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2022-12-06 20:14 UTC, rustydb requested changes

2022-12-06 20:14 UTC, rustydb commented on workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
> +        image: registry.local/artifactory.algol60.net/csm-docker/unstable/cf-gitea-import:1.8.0-alpha.19_6747be7
Why does this switch to unstable?

2022-12-07 00:07 UTC, jsollom-hpe approved these changes

2022-12-07 00:07 UTC, jsollom-hpe commented on workflows/iuf/operations/vcs-upload/vcs-upload-content.yaml
> +        image: registry.local/artifactory.algol60.net/csm-docker/stable/cf-gitea-import:1.8.0-alpha.19_6747be7
Eventually, we'll want to use a stable release, not an alpha.

2022-12-09 17:39 UTC, atifsyedali approved these changes

2022-12-12 20:11 UTC, merged