CASMINST-5779: Patch instructdions for 1.3.1
Cray-HPE/docs-csm pull request #3002
Opened 2023-01-11 17:26 UTC by jeremy-duckworth

# Description

1.3.0 to 1.3.1 patch instructions. Includes call-out to 1.3.0 upgrade instructions if upgrading (from 1.2.x), vs. patching.

# Checklist Before Merging
- [ ] Merge https://github.com/Cray-HPE/csm/pull/1616 (before testing patch process)
- [ ] Teams (managers) to review `Bug Fixes and Improvements` and `Known Issues` (currently a placeholder)

- [X] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-01-14 00:18 UTC, djlapenta approved these changes
I do not have anything to add around known issues as we called the ceph latency stuff out, already, in the 1.3 release notes.  I checked the bug fix and improvement section as well and went through all of our 1.3.1 tickets as well.

2023-01-17 20:06 UTC, rustydb requested changes

2023-01-17 20:06 UTC, rustydb commented on upgrade/1.3.1/README.md
> +   ncn-m001# script -af csm-update.$(date +%Y-%m-%d).txt
All the prompts need to be moved out of the code blocks in order to be copy-paste friendly.

https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#command-prompt-location

2023-01-17 20:47 UTC, rustydb approved these changes

2023-01-17 20:50 UTC, merged