CASMTRIAGE-4836 update storage rebuild procedure and fix issue unmanaged osds
Cray-HPE/docs-csm pull request #3086
Opened 2023-01-25 20:57 UTC by leliasen-hpe

# Description

Update storage rebuild procedure and fix issue unmanaged osds

# Checklist Before Merging

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-01-25 21:02 UTC, cdelatte-hpe requested changes

2023-01-25 21:02 UTC, cdelatte-hpe commented on operations/node_management/Rebuild_NCNs/Prepare_Storage_Nodes.md
> +Upload ceph container images into nexus.
we should be specific and tell then what to name it and where to put it.    we can also make this a script file and put in the docs-csm/scripts dir and just have copy out, chmod, and a run example.

2023-02-07 18:57 UTC, rgross727 approved these changes

2023-02-07 19:03 UTC, leliasen-hpe commented
/backport release/1.4

2023-02-07 19:15 UTC, leliasen-hpe commented
backport to 1.4 was done from main PR: https://github.com/Cray-HPE/docs-csm/pull/3251

2023-02-07 19:18 UTC, cdelatte-hpe approved these changes

2023-02-07 19:53 UTC, cdelatte-hpe approved these changes

2023-02-07 22:55 UTC, rustydb approved these changes

2023-02-07 23:41 UTC, merged