First pass at CSM 1.3.2 patch instructions, and add upgrade steps for CASMHMS-5911
Cray-HPE/docs-csm pull request #3280
Opened 2023-02-10 16:36 UTC by rsjostrand-hpe

# Description

First pass at CSM 1.3.2 patch instructions.
    
CASMHMS-5911: Added steps to make the needed changes for the cray-hms-hmcollector chart to be accessible at `hmcollector.hmnlb.$SYSTEM_NAME.$SITE_DOMAIN` on upgrades to CSM 1.3.2

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-02-10 19:29 UTC, shunr-hpe approved these changes

2023-02-10 20:29 UTC, nrockershousen commented on upgrade/1.3.2/README.md
> +This document guides an administrator through the patch update to Cray Systems Management `v1.3.2` from `v1.3.1`.
```suggestion
This document guides an administrator through the patch update to Cray Systems Management (CSM) `v1.3.2` from `v1.3.1`.
```

2023-02-10 20:29 UTC, nrockershousen commented on upgrade/1.3.2/README.md
> +1. Add customizations for the `cray-hms-hmcollector` helm chart:
```suggestion
1. Add customizations for the `cray-hms-hmcollector` Helm chart:
```

2023-02-10 20:29 UTC, nrockershousen approved these changes

2023-02-10 21:32 UTC, rustydb requested changes
Requires this to merge: https://github.com/Cray-HPE/csm/pull/1828#pullrequestreview-1294051336

Marking as "needs work" to block someone from merging this in the meantime.

2023-02-12 22:56 UTC, johren-hpe requested changes

2023-02-12 22:56 UTC, johren-hpe commented on upgrade/1.3.2/README.md
> +* Fixed a scale issue with the `/v1/hardware` API in the System Layout Service (SLS) causing the service become deadlocked.
```suggestion
* Fixed a scale issue with the `/v1/hardware` API in the System Layout Service (SLS) causing the service to become deadlocked.
```

2023-02-12 22:56 UTC, johren-hpe commented on upgrade/1.3.2/README.md
> +   CSM_DISTDIR="$(pwd)/csm-1.3.1"
```suggestion
   CSM_DISTDIR="$(pwd)/csm-1.3.2"
```

2023-02-13 20:58 UTC, gbaker-hpe approved these changes

2023-02-13 20:58 UTC, rustydb approved these changes

2023-02-13 20:59 UTC, merged