CASMTRIAGE-4824 make install_csi hook more robust
Cray-HPE/docs-csm pull request #3289
Opened 2023-02-13 15:16 UTC by leliasen-hpe

# Description

Make install_csi hook more robust. It will check both sp3 and sp4 for link to install csi and will only fail if unable to install csi, independent of installing other repositories. Provides an error message if nexus appears to be down.

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-02-13 15:20 UTC, leliasen-hpe commented
/backport release/1.4

2023-02-13 20:19 UTC, rustydb commented
Feedback on the backport also applies here: https://github.com/Cray-HPE/docs-csm/pull/3290#pullrequestreview-1296379186

2023-02-13 20:50 UTC, gbaker-hpe requested changes
Let's reduce the logic checking in this to avoid having to maintain it when we move so SP5 and beyond.  We can ensure the CSI build publishes to all of these repos and in the future, create a non-specific repo for packages that can be used in all distros.

2023-02-21 20:43 UTC, denniswalker approved these changes

2023-02-21 20:45 UTC, merged