Slight change in expected output of logwrite_root_secrets_to_vault.py
Cray-HPE/docs-csm pull request #3344
Opened 2023-02-24 06:44 UTC by SavioJoshua

# Description

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-02-24 20:02 UTC, rustydb approved these changes

2023-02-24 20:53 UTC, gbaker-hpe requested changes
@ganeshs-hpe Do you know why we're querying Vault using HTTP (not HTTPS) and an IP instead of a hostname?

The IP opens us up to man in the middle attacks and HTTP is not a secure transport which is important since an SSH private key is being transmitted.

I know you copied what was already written, but do you know why this is setup this way?  Is it just the output that shows HTTP?

I think we want to evaluate this script before we proceed to ensure we're not doing something that is worth correcting.

2023-03-02 20:39 UTC, denniswalker commented
/backport main

2023-03-02 20:40 UTC, denniswalker approved these changes

2023-03-02 20:41 UTC, merged