CASMTRIAGE-4865 - Ensure switches have SNMP configured (Papaya)
Cray-HPE/docs-csm pull request #3373
Opened 2023-02-28 23:31 UTC by gbaker-hpe

jira-ticket: "CASMTRIAGE-4865"
csm-version: "1.4"
shasta-version: "Alice"
---

The CSM install and upgrade now explicitly ask admins to ensure that SNMP is configured on the management network switches so that REDS Hardware Discovery will be successful.

Added information about CANU custom configs to the CSM documentation as a reference for SNMP configurations.

Generally improved SNMP documentation information and backlinking.

- [X]  If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [X]  If I added a new directory, I also updated .github/CODEOWNERS with the corresponding team in [Cray-HPE][2].
- [X]  My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

2023-03-01 18:28 UTC, trad511 approved these changes

2023-03-01 20:13 UTC, rustydb requested changes
Same comment as https://github.com/Cray-HPE/docs-csm/pull/3361#pullrequestreview-1320554092

2023-03-01 21:01 UTC, lukebates123 approved these changes

2023-03-02 00:06 UTC, rustydb approved these changes

2023-03-02 00:06 UTC, merged