CASMINST-6060: add the embedded repo to csm-config-management
Cray-HPE/docs-csm pull request #3425
Opened 2023-03-08 21:59 UTC by heemstra

# Description

This commit amends Nexus_Import_Embedded_Repo.md to include adding the embedded repo to the list of repos csm-config-management adds via ansible during image customization and/or node personalization.

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-03-08 22:09 UTC, phalseth-hpe approved these changes

2023-03-09 20:38 UTC, rustydb requested changes

2023-03-09 20:38 UTC, rustydb commented on operations/package_repository_management/Nexus_Import_Embedded_Repo.md
> +```bash
These need to be tabbed over to align with the step.

2023-03-09 20:38 UTC, rustydb requested changes

2023-03-09 20:38 UTC, rustydb commented on operations/package_repository_management/Nexus_Import_Embedded_Repo.md
> +Commit and push the change.
Should this be a step? (e.g. 1. Commit and push the change)

2023-03-09 20:43 UTC, rustydb approved these changes

2023-03-09 20:45 UTC, merged