CASM-3884: Upgrade script for Prometheus Operator to latest version
Cray-HPE/docs-csm pull request #3487
Opened 2023-03-21 10:24 UTC by shreni123

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

CASM-3884: Upgrade Prometheus Operator to latest version
This PR includes upgrade script changes with respect to Prometheus-operator upgrade from 9.3.1 to 45.1.1 (latest) version.
## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves 
https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-282
https://jira-pro.its.hpecorp.net:8443/browse/CASM-3884

## Testing

_List the environments in which these changes were tested._

### Tested on:

Wasp & Gamora

### Test description: (LOGS)

ncn-m001:/mnt/developer/shreni/migration # ./upgrade.sh
Checking for chart version of cray-sysmgmt-health
Get PV for both prometheus and Alertmanager
Prometheus PV: pvc-5311abcd-18da-484a-ba3b-363e11b75986
Alertmanager PV: pvc-5f237239-7bfc-4abd-836e-0586622fb53f
persistentvolume/pvc-5311abcd-18da-484a-ba3b-363e11b75986 patched
persistentvolume/pvc-5f237239-7bfc-4abd-836e-0586622fb53f patched
W0321 10:02:31.950164  259623 warnings.go:70] rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
W0321 10:02:31.954006  259623 warnings.go:70] rbac.authorization.k8s.io/v1beta1 Role is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 Role
W0321 10:02:31.959220  259623 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0321 10:02:31.964999  259623 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0321 10:02:31.993981  259623 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0321 10:02:31.994470  259623 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0321 10:02:31.994514  259623 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0321 10:02:31.995282  259623 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0321 10:02:31.995292  259623 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0321 10:02:31.995338  259623 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0321 10:02:31.995706  259623 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0321 10:02:32.083201  259623 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0321 10:02:32.220833  259623 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
release "cray-sysmgmt-health" uninstalled
persistentvolumeclaim "prometheus-cray-sysmgmt-health-promet-prometheus-db-prometheus-cray-sysmgmt-health-promet-prometheus-0" deleted
persistentvolumeclaim "alertmanager-cray-sysmgmt-health-promet-alertmanager-db-alertmanager-cray-sysmgmt-health-promet-alertmanager-0" deleted
Verifying whether PVs became Released or not.
Both Prometheus and Alertmanager PVs are Released
Deleting cray-sysmgmt-health-promet-kubelet service in kube-system namespace.
service "cray-sysmgmt-health-promet-kubelet" deleted
Deleting sysmgmt-health existing CRDs
customresourcedefinition.apiextensions.k8s.io "alertmanagers.monitoring.coreos.com" deleted
customresourcedefinition.apiextensions.k8s.io "podmonitors.monitoring.coreos.com" deleted
customresourcedefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" deleted
customresourcedefinition.apiextensions.k8s.io "prometheusrules.monitoring.coreos.com" deleted
customresourcedefinition.apiextensions.k8s.io "servicemonitors.monitoring.coreos.com" deleted
customresourcedefinition.apiextensions.k8s.io "thanosrulers.monitoring.coreos.com" deleted
persistentvolume/pvc-5311abcd-18da-484a-ba3b-363e11b75986 patched
persistentvolume/pvc-5f237239-7bfc-4abd-836e-0586622fb53f patched
Verifying whether PV became Available or not.
PVs are not Available. Verify if PV exists or not.
Prometheus PV: pvc-5311abcd-18da-484a-ba3b-363e11b75986
Alertmanager PV: pvc-5f237239-7bfc-4abd-836e-0586622fb53f

### K8s 1.22 deprecation:

Tested on - Pluto

ncn-m001:/mnt/developer/shreni/dep # ./pluto detect-helm | awk '/NAME|sysmgmt-health/'
NAME                                                                       KIND                             VERSION                                REPLACEMENT                       REMOVED   DEPRECATED   REPL AVAIL
cray-sysmgmt-health/cray-sysmgmt-health-prometheus-node-exporter           PodSecurityPolicy                policy/v1beta1                                                           false     true         true
cray-sysmgmt-health/cray-sysmgmt-health-kube-p-alertmanager                PodSecurityPolicy                policy/v1beta1                                                           false     true         true
cray-sysmgmt-health/cray-sysmgmt-health-kube-p-operator                    PodSecurityPolicy                policy/v1beta1                                                           false     true         true
cray-sysmgmt-health/cray-sysmgmt-health-kube-p-prometheus                  PodSecurityPolicy                policy/v1beta1                                                           false     true         true

2023-03-21 15:36 UTC, rambabubolla approved these changes

2023-03-23 09:20 UTC, shreni123 commented on upgrade/scripts/upgrade/prerequisites.sh
> +        "${locOfScript}/../upgrade/upgrade-state.sh"
done.

2023-03-23 09:26 UTC, rambabubolla approved these changes

2023-05-15 22:12 UTC, bklei approved these changes

2023-05-16 01:25 UTC, johren-hpe requested changes
Also need to make changes in https://github.com/Cray-HPE/docs-csm/blob/main/upgrade/scripts/upgrade/util/update-customizations.sh to match the changes made in https://github.com/Cray-HPE/csm/pull/1913/files.

2023-05-16 19:10 UTC, rustydb approved these changes

2023-05-16 19:18 UTC, johren-hpe approved these changes

2023-05-16 19:20 UTC, merged