Bonded UAN net DOCS
Cray-HPE/docs-csm pull request #3534
Opened 2023-03-28 18:04 UTC by lukebates123

# Description

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-03-28 18:24 UTC, kosonenj approved these changes

2023-03-28 19:01 UTC, trad511 requested changes
Do any of the 10G configurations require a block of ports to be forced at 10G?

2023-03-30 19:05 UTC, trad511 approved these changes

2023-03-30 19:07 UTC, rustydb approved these changes

2023-03-30 19:08 UTC, merged