CASMNET-2127 | qlogic driver crash known issue doc
Cray-HPE/docs-csm pull request #3822
Opened 2023-05-24 16:26 UTC by kosonenj

# Description

Known  issue documentation for Qlogic driver crash triaged in CASMTRIAGE-5033

Relates to:
- https://jira-pro.it.hpe.com:8443/browse/CASMNET-2127
- https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-5033

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-06-07 19:14 UTC, rustydb commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +```bash
```suggestion
```text
```

2023-06-07 19:14 UTC, rustydb commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +```bash
```suggestion
```text
```

2023-06-07 19:14 UTC, rustydb commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +```bash
```suggestion
```text
```

2023-06-07 19:14 UTC, rustydb commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +Too correct the issue, please login to both the VSX pair switches and correct the configuration of these lags to use "vlan trunk native 10":
```suggestion
Too correct the issue, please login to both the VSX pair switches and correct the configuration of these lags to use `vlan trunk native 10`:
```

2023-06-07 19:15 UTC, rustydb commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +In this example of the problem you can see that the lags 10,12,14 which are the lags for the storage back channel communication have applied configuration of "vlan trunk native 1". Which is wrong.
```suggestion
In this example of the problem you can see that the lags 10,12,14 which are the lags for the storage back channel communication have applied configuration of `vlan trunk native 1`. Which is wrong.
```

2023-06-07 19:25 UTC, nrockershousen commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +In some failover/maintenance scenarios users may experience Qlogic driver crash on the storage nodes. This issue is usually tied to network event's such as an reboot of a switch in the VSX pair but c
```suggestion
In some failover/maintenance scenarios users may experience Qlogic driver crash on the storage nodes. This issue is usually tied to network events, such as a reboot of a switch in the VSX pair, but can also occur without user intervention in rare events.
```

2023-06-07 19:25 UTC, nrockershousen commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +The configuration is fixed in Canu versions 2.3 and above.
```suggestion
The configuration is fixed in CANU versions 2.3 and above.
```
CANU is all uppercase throughout the rest of the documentation.

2023-06-07 19:25 UTC, nrockershousen commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +Upgrade Canu to 2.3 or above, regenerate the configuration and apply it the VSX-pair that hosts the storage nodes.
```suggestion
Upgrade CANU to version 2.3 or above, regenerate the configuration, and then apply it the VSX-pair that hosts the storage nodes.
```

2023-06-07 19:25 UTC, nrockershousen commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +Too correct the issue, please login to both the VSX pair switches and correct the configuration of these lags to use "vlan trunk native 10":
```suggestion
To correct the issue, log in to both the VSX pair switches and correct the configuration of these lags to use "vlan trunk native 10":
```

2023-06-07 19:25 UTC, nrockershousen commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +In this example of the problem you can see that the lags 10,12,14 which are the lags for the storage back channel communication have applied configuration of "vlan trunk native 1". Which is wrong.
```suggestion
In the following example, lags 10, 12, and 14, which are the lags for the storage back channel communication, have a configuration of "vlan trunk native 1". This is incorrect.
```

2023-06-07 19:25 UTC, nrockershousen commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +Working with vendor to fix qlogic driver code, once fix is released we will add the new qlogic driver to our firmware pack.
```suggestion
The vendor is working to fix the Qlogic driver code. Once a fix is released, the new Qlogic driver will be added to the firmware pack.
```

2023-06-14 19:02 UTC, rustydb requested changes

2023-06-14 19:02 UTC, rustydb commented on .spelling
> +qlogic
```suggestion
QLogic
qlogic
```

nit: when using the formal name, it should be "QLogic."

2023-06-14 19:02 UTC, nrockershousen commented on troubleshooting/known_issues/qlogic_driver_crash.md
> +Too correct the issue, please login to both the VSX pair switches and correct the configuration of these lags to use `vlan trunk native 10`:
```suggestion
To correct the issue, log in to both the VSX pair switches and correct the configuration of these lags to use `vlan trunk native 10`:
```

2023-06-20 19:05 UTC, nrockershousen approved these changes

2023-06-26 19:11 UTC, rustydb approved these changes

2023-06-26 19:14 UTC, merged