CASMNET-2134 | Improve network install docs
Cray-HPE/docs-csm pull request #3841
Opened 2023-05-31 20:54 UTC by kosonenj

# Description

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-06-02 14:54 UTC, lukebates123 requested changes

2023-06-02 14:54 UTC, lukebates123 commented on operations/network/management_network/README.md
> +| Current switch configurations are CANU-generated and need to go to 1.3          | [`1.3 (Preconfig)` to 1.3](1.2_to_1.3_upgrade.md) |
We should probably update or remove the CSM version numbers throughout the net docs.

2023-06-12 15:55 UTC, kosonenj commented
Lintcheck fails because of: 

2 links checked.
  [✖] ../../troubleshooting/known_issues/qlogic_driver_crash.md → Status: 400
  
 PR https://github.com/Cray-HPE/docs-csm/pull/3822 Needs to be merged first

2023-06-14 19:13 UTC, rustydb requested changes

2023-06-14 19:13 UTC, rustydb commented on operations/network/management_network/firmware/update_management_network_firmware.md
>  | Mellanox SN2100 Switch Series | 3.9.3210|
Same comment https://github.com/Cray-HPE/docs-csm/pull/3814#discussion_r1222053008.

2023-06-14 19:41 UTC, denniswalker commented on install/csm-install/README.md
> +#### Management network
Can we move this to its own document and then link here and also from install/common-pre-install/README.md#configure-the-management-network-with-canu

Separately, is this the same set of concerns for upgrades?

2023-06-20 19:05 UTC, nrockershousen approved these changes

2023-06-26 19:24 UTC, rustydb commented
Rebased on main after merging #3822 and #3814

2023-07-06 17:55 UTC, closed without merging

2023-07-06 17:56 UTC, kosonenj commented
closing because of merge conficts from pet changes and want to make cleaner PR