CASMPET-6613 Add shfmt
Cray-HPE/docs-csm pull request #3846
Opened 2023-06-01 19:18 UTC by kburns-hpe

This adds running shellcheck and shfmt to the build pipeline. This will allow for a more consistent formatting among teams and reduce the need for reviewers to check for these issues.

2023-06-01 19:23 UTC, mtupitsyn approved these changes

2023-06-01 19:33 UTC, kburns-hpe commented
Looks like shellcheck was already in there. Removing it in favor of running shfmt in a similar way.

2023-06-02 19:17 UTC, rustydb commented
Discussing with libcsm/docs-csm ppl, this may need to merge with the shellcheck workflow and/or align with what we're doing in libcsm (since docs-csm workflows are a little stale). Will get back to you asap, and get this in.

2023-06-02 19:24 UTC, rustydb requested changes
Please merge this with the existing shellcheck workflow, then we don't have to manage yet another workflow in the branch protection settings.

2023-06-20 20:43 UTC, rustydb approved these changes

2023-06-21 17:39 UTC, merged