CASMTRIAGE-5504 exit upload-ncn-images.sh if CSM_RELEASE is not set
Cray-HPE/docs-csm pull request #3868
Opened 2023-06-07 21:17 UTC by leliasen-hpe

# Description
upload-ncn-images.sh is run as part of 1.4.1 patch. This script will run for many minutes before exiting if CSM_RELEASE variable is not set. This adds an early exit to the script if CSM_RELEASE is not set.

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-06-07 21:30 UTC, bklei approved these changes

2023-06-12 16:03 UTC, ndavidson-hpe approved these changes

2023-06-12 16:04 UTC, johren-hpe requested changes

2023-06-12 16:04 UTC, johren-hpe commented on upgrade/scripts/upgrade/upload-ncn-images.sh
> +export CSM_ARTI_DIR
Does CSM_RELEASE need to be exported, too?

2023-06-12 16:07 UTC, johren-hpe commented on upgrade/scripts/upgrade/upload-ncn-images.sh
> +export CSM_ARTI_DIR
Nevermind.  I see now that it is expected to be exported and doesn't get reassigned.

2023-06-12 16:07 UTC, johren-hpe approved these changes

2023-06-12 19:38 UTC, merged