Configure smartmon metrics on storage nodes in 1.3.5 (CASMINST-6562)
Cray-HPE/docs-csm pull request #4052
Opened 2023-07-26 20:30 UTC by bklei

### Summary and Scope

Include smart-mon rpm in 1.3.5 patch

### Issues and Related PRs

* https://jira-pro.it.hpe.com:8443/browse/CASMINST-6562

### Testing

Build output:

```
[2023-07-26T19:52:08.957Z] 2023-07-26 19:52:08,832	INFO	Adding password to password_mgr for https://artifactory.algol60.net/artifactory/

[2023-07-26T19:52:08.957Z] 2023-07-26 19:52:08,833	INFO	adding basic_auth_handler to opener

[2023-07-26T19:52:08.957Z] 2023-07-26 19:52:08,835	INFO	Reading https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/noos/

[2023-07-26T19:52:09.219Z] 2023-07-26 19:52:09,137	INFO	https://artifactory.algol60.net/artifactory/ is the parent url of https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/noos/

[2023-07-26T19:52:09.482Z] 2023-07-26 19:52:09,417	INFO	[200 OK] https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/noos/smart-mon/noarch/smart-mon-1.0.3-1.noarch.rpm
```

Was a fresh Install tested? N
Was an Upgrade tested?      N - N/A
Was a Downgrade tested?     N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A

### Risks and Mitigations

Low

### Requires:

* Nothing

2023-07-26 21:44 UTC, bo-quan approved these changes

2023-07-27 18:17 UTC, mharding-hpe requested changes

2023-07-27 18:17 UTC, mharding-hpe commented on install/deploy_non-compute_nodes.md
> +    1. [Enable `Smartmon` Metrics on Storage NCNs](#26-enable-smartmon-metrics-on-storage-ncns)
```suggestion
    1. [Enable `smartmon` metrics on storage NCNs](#26-enable-smartmon-metrics-on-storage-ncns)
```

2023-07-27 18:17 UTC, mharding-hpe commented on install/deploy_non-compute_nodes.md
> +   ```
````suggestion
### 2.6 Enable `smartmon` metrics on storage NCNs

(`ncn-m001#`) Install the `smart-mon` RPM on storage NCNs, and reconfigure the `node-exporter` to provide `smartmon` metrics.

```bash
/usr/share/doc/csm/scripts/operations/ceph/enable-smart-mon-storage-nodes.sh
```
````

2023-07-27 18:17 UTC, mharding-hpe commented on scripts/operations/ceph/enable-smart-mon-storage-nodes.sh
> +  ssh ${storage_node} ${ssh_options} "zypper in ${smartmon_url} && systemctl enable smart && systemctl restart smart"
As written, I think this top-level script will pass even if any of the commands being run via SSH fail. Is that the desired behavior?

2023-07-27 18:17 UTC, mharding-hpe commented on upgrade/1.3.5/README.md
> +1. [Enable `Smartmon` Metrics on Storage NCNs](#enable-smartmon-metrics-on-storage-ncns)
```suggestion
1. [Enable `smartmon` metrics on storage NCNs](#enable-smartmon-metrics-on-storage-ncns)
```

2023-07-27 18:17 UTC, mharding-hpe commented on upgrade/1.3.5/README.md
> +## Enable `Smartmon` Metrics on Storage NCNs
```suggestion
## Enable `smartmon` metrics on storage NCNs
```

2023-07-27 18:17 UTC, mharding-hpe commented on upgrade/1.3.5/README.md
> +   ```
````suggestion
(`ncn-m001#`) Install the `smart-mon` RPM on storage NCNs, and reconfigure the `node-exporter` to provide `smartmon` metrics.

```bash
/usr/share/doc/csm/scripts/operations/ceph/enable-smart-mon-storage-nodes.sh
```
````

2023-07-27 18:17 UTC, mharding-hpe commented on upgrade/Stage_0_Prerequisites.md
> +- [Stage 0.6 - Enable `Smartmon` Metrics on Storage NCNs](#stage-06---enable-smartmon-metrics-on-storage-ncns)
```suggestion
- [Stage 0.6 - Enable `smartmon` metrics on storage NCNs](#stage-06---enable-smartmon-metrics-on-storage-ncns)
```

2023-07-27 18:17 UTC, mharding-hpe commented on upgrade/Stage_0_Prerequisites.md
> +## Stage 0.6 - Enable `Smartmon` Metrics on Storage NCNs
```suggestion
## Stage 0.6 - Enable `smartmon` metrics on storage NCNs
```

2023-07-27 18:17 UTC, mharding-hpe commented on upgrade/Stage_0_Prerequisites.md
> +   ```
````suggestion
(`ncn-m001#`) Install the `smart-mon` RPM on storage NCNs, and reconfigure the `node-exporter` to provide `smartmon` metrics.

```bash
/usr/share/doc/csm/scripts/operations/ceph/enable-smart-mon-storage-nodes.sh
```
````

2023-08-01 13:31 UTC, closed without merging