Add script to enable goss-servers after update (CASMTRIAGE-6046)
Cray-HPE/docs-csm pull request #4285
Opened 2023-09-18 16:10 UTC by bklei

### Summary and Scope

Add step to enable/start goss-servers after update.

### Issues and Related PRs

* https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6046

### Testing

fanta:

```
ncn-m001:~/brad # ./upgrade-test-rpms.sh
Installing updated versions of csm-testing goss-servers craycli rpms
ncn-s002: Loading repository data...
ncn-s003: Loading repository data...
ncn-s001: Loading repository data...
ncn-s002: Reading installed packages...
ncn-s003: Reading installed packages...
ncn-s001: Reading installed packages...
ncn-s004: Loading repository data...
ncn-s002: 'craycli' is already installed.
ncn-s002: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-s002: 'goss-servers' is already installed.
ncn-s002: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-s002: 'csm-testing' is already installed.
ncn-s002: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-s002: Resolving package dependencies...
ncn-s003: 'craycli' is already installed.
ncn-s003: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-s003: 'goss-servers' is already installed.
ncn-s003: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-s003: 'csm-testing' is already installed.
ncn-s003: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-s003: Resolving package dependencies...
ncn-s001: 'craycli' is already installed.
ncn-s001: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-s001: 'goss-servers' is already installed.
ncn-s001: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-s001: 'csm-testing' is already installed.
ncn-s001: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-s001: Resolving package dependencies...
ncn-s004: Reading installed packages...
ncn-m001: Loading repository data...
ncn-s004: 'craycli' is already installed.
ncn-s004: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-s004: 'goss-servers' is already installed.
ncn-s004: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-s004: 'csm-testing' is already installed.
ncn-s004: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-s004: Resolving package dependencies...
ncn-m001: Reading installed packages...
ncn-m001: 'craycli' is already installed.
ncn-m001: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-m001: 'goss-servers' is already installed.
ncn-m001: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-m001: 'csm-testing' is already installed.
ncn-m001: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-m001: Resolving package dependencies...
ncn-w003: Loading repository data...
ncn-w003: Reading installed packages...
ncn-s002: Nothing to do.
ncn-s003: Nothing to do.
ncn-s001: Nothing to do.
ncn-w003: 'craycli' is already installed.
ncn-w003: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-w003: 'goss-servers' is already installed.
ncn-w003: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-w003: 'csm-testing' is already installed.
ncn-w003: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-w003: Resolving package dependencies...
ncn-m002: Loading repository data...
ncn-m002: Reading installed packages...
ncn-w001: Loading repository data...
ncn-w001: Reading installed packages...
ncn-m002: 'craycli' is already installed.
ncn-m002: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-m002: 'goss-servers' is already installed.
ncn-m002: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-m002: 'csm-testing' is already installed.
ncn-m002: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-m002: Resolving package dependencies...
ncn-m001: Nothing to do.
ncn-w001: 'craycli' is already installed.
ncn-w001: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-w001: 'goss-servers' is already installed.
ncn-w001: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-w001: 'csm-testing' is already installed.
ncn-w001: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-w001: Resolving package dependencies...
ncn-s004: Nothing to do.
ncn-m002: Nothing to do.
ncn-m003: Loading repository data...
ncn-m003: Reading installed packages...
ncn-w001: Nothing to do.
ncn-m003: 'craycli' is already installed.
ncn-m003: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-m003: 'goss-servers' is already installed.
ncn-m003: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-m003: 'csm-testing' is already installed.
ncn-m003: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-m003: Resolving package dependencies...
ncn-w003: Nothing to do.
ncn-m003: Nothing to do.
ncn-w002: Loading repository data...
ncn-w002: Reading installed packages...
ncn-w002: 'craycli' is already installed.
ncn-w002: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-w002: 'goss-servers' is already installed.
ncn-w002: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-w002: 'csm-testing' is already installed.
ncn-w002: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-w002: Resolving package dependencies...
ncn-w004: Loading repository data...
ncn-w004: Reading installed packages...
ncn-w004: 'craycli' is already installed.
ncn-w004: No update candidate for 'craycli-0.74.0-1.x86_64'. The highest available version is already installed.
ncn-w004: 'goss-servers' is already installed.
ncn-w004: No update candidate for 'goss-servers-1.15.53-1.noarch'. The highest available version is already installed.
ncn-w004: 'csm-testing' is already installed.
ncn-w004: No update candidate for 'csm-testing-1.15.53-1.noarch'. The highest available version is already installed.
ncn-w004: Resolving package dependencies...
ncn-w002: Nothing to do.
ncn-w004: Nothing to do.
Enabling and starting goss-servers
ncn-s001: Created symlink /etc/systemd/system/multi-user.target.wants/goss-servers.service → /etc/systemd/system/goss-servers.service.
ncn-s003: Created symlink /etc/systemd/system/multi-user.target.wants/goss-servers.service → /etc/systemd/system/goss-servers.service.
ncn-s002: Created symlink /etc/systemd/system/multi-user.target.wants/goss-servers.service → /etc/systemd/system/goss-servers.service.
ncn-s004: Created symlink /etc/systemd/system/multi-user.target.wants/goss-servers.service → /etc/systemd/system/goss-servers.service.
ncn-w001: Created symlink /etc/systemd/system/multi-user.target.wants/goss-servers.service → /etc/systemd/system/goss-servers.service.
ncn-m002: Created symlink /etc/systemd/system/multi [...]

2023-09-18 16:14 UTC, leliasen-hpe approved these changes

2023-09-18 16:16 UTC, heemstra approved these changes

2023-09-18 16:29 UTC, kimjensen-hpe approved these changes

2023-09-18 19:04 UTC, rustydb requested changes

2023-09-18 19:04 UTC, rustydb commented on upgrade/scripts/upgrade/util/upgrade-test-rpms.sh
> +
```suggestion
set -euo pipefail
```

2023-09-18 19:04 UTC, rustydb commented on upgrade/scripts/upgrade/util/upgrade-test-rpms.sh
> +pdsh -b -w ${ncns} 'systemctl enable goss-servers && systemctl start goss-servers'
Enable `pdsh` to fail on a non-zero return code with `-S`.

```suggestion
pdsh -S -b -w ${ncns} 'zypper install -y csm-testing goss-servers craycli'

echo "Enabling and starting goss-servers"
pdsh -S -b -w ${ncns} 'systemctl enable goss-servers && systemctl start goss-servers'
```

2023-09-19 19:34 UTC, rustydb approved these changes

2023-09-19 19:51 UTC, merged