CASMTRIAGE-6077: upgrade CFS/IMS charts after postgres upgrade is done
Cray-HPE/docs-csm pull request #4300
Opened 2023-09-25 20:15 UTC by bo-quan

# Description
After postgres-operator is upgraded, postgres pods will take more than 10 minutes to be upgraded and ready. Moving CFS/IMS chart upgrade toward the end of prerequisites script (after FINISH_NLS_UPGRADE step) should be long enough to ensure its upgrade success.

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-09-25 20:25 UTC, kimjensen-hpe approved these changes

2023-09-25 20:31 UTC, mharding-hpe approved these changes

2023-09-26 19:07 UTC, rustydb requested changes

2023-09-26 19:07 UTC, rustydb commented on upgrade/scripts/upgrade/prerequisites.sh
> +for chart_name in cfs-ara cfs-hwsync-agent cfs-trust cray-bos cray-cfs-api cray-cfs-batcher cray-cfs-operator cray-ims csm-ssh-keys; do
```suggestion
# And relatedly, upgrade cray-bos to address CASMTRIAGE-6009
CHARTS=(
'cfs-ara'
'cfs-hwsync-agent'
'cfs-trust'
'cray-bos'
'cray-cfs-api'
'cray-cfs-batcher'
'cray-cfs-operator'
'cray-ims'
'csm-ssh-keys'
)
for chart_name in "${CHARTS[@]}"; do
```

Use a list so line 1305 is nice and short.

2023-09-26 19:20 UTC, rustydb commented
/backport release/1.6

2023-09-26 19:34 UTC, merged