CASMCMS-8720: Update docs for CFS v3 and paging (1.5)
Cray-HPE/docs-csm pull request #4321
Opened 2023-09-28 18:06 UTC by rbak-hpe

# Description

Updates the CFS docs for the v3 api and paging.  Also re-organizes and cleans up the CFS docs in general.

Relates to:
- CASMCMS-8720

# Checklist

- [X] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [X] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2023-09-28 18:10 UTC, mharding-hpe requested changes

2023-09-28 18:10 UTC, mharding-hpe commented on operations/network/Gateway_Testing.md
If you aren't making the test changes in this PR, then I think these test output changes shouldn't be included.

2023-09-28 18:18 UTC, rbak-hpe commented on operations/network/Gateway_Testing.md
I've dropped this change

2023-09-28 18:21 UTC, mharding-hpe approved these changes

2023-09-29 12:45 UTC, rbak-hpe commented
This is a scaled down back-port of the changes in https://github.com/Cray-HPE/docs-csm/pull/4283 and can be merged anytime.

2023-10-02 19:04 UTC, rustydb approved these changes

2023-10-02 19:05 UTC, merged