CASMMON-350: Bug fixes for SMART data on UAN docs
Cray-HPE/docs-csm pull request #4461
Opened 2023-11-02 12:19 UTC by shreni123

https://jira-pro.it.hpe.com:8443/browse/CASMMON-350

Bug fixes for SMART data on UAN docs

2023-11-02 19:08 UTC, heemstra approved these changes

2023-11-02 19:13 UTC, rustydb requested changes

2023-11-02 19:13 UTC, rustydb commented on operations/system_management_health/uan_node_exporter_configs.md
> +   Here, `/etc/cray/upgrade/csm/csm-1.4.3/tarball/csm-1.4.3/helm/` is the path of the `cray-sysmgmt-health` chart.
This should use the `CSM_RELEASE` variable in `/etc/environment` instead of `1.4.3`.

2023-11-03 19:05 UTC, rustydb approved these changes

2023-11-03 19:05 UTC, merged