HMS Rapid Redeploy Documentation and scripts CASMHMS-5772/5773/5774
Cray-HPE/docs-csm pull request #4683
Opened 2024-02-09 18:10 UTC by mbuchmann-hpe

# Description
Documentation and scripts for the Rapid Redeploy process (backup and restore).

Tested on Wasp as part of the process for implementation on UKMet

- CASMHMS-5772
- CASMHMS-5773
- CASMHMS-5774

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-02-09 21:13 UTC, shunr-hpe approved these changes

2024-02-12 19:41 UTC, rustydb requested changes

2024-02-12 19:41 UTC, rustydb commented on operations/Backup_HMS.md
![image](https://github.com/Cray-HPE/docs-csm/assets/7772179/c0e50413-5030-4aaa-a83b-6c3fe8fcb32e)

The indentation is breaking the ordered list.


For anything that's a part of a list item, it should be indented to at least the first character in the first line.

e.g.

````markdown
1. Lorem ipsom

   Another statement, aligned with "L"

1. Another step

   ```bash
   echo "hello world"
   ```

````

2024-02-12 22:08 UTC, mbuchmann-hpe commented on operations/Backup_HMS.md
Updated indentation

2024-02-13 20:09 UTC, rustydb commented on operations/hardware_state_manager/HSM_Backup_User_Data.md
The indentation breaks the ordered list and formatting.

![image](https://github.com/Cray-HPE/docs-csm/assets/7772179/8ee8ff4e-d00b-4390-841c-20d07e7525f8)

For anything that's a part of a list item, it should be indented to at least the first character in the first line.

e.g.

````markdown
1. Lorem ipsom

   Another statement, aligned with "L"

1. Another step

   ```bash
   echo "hello world"
   ```

````

2024-02-13 22:47 UTC, rustydb requested changes
Indentation is broken, see comment.

2024-02-20 20:11 UTC, rustydb approved these changes

2024-02-20 20:11 UTC, merged