CASMTRIAGE-6625: Add known issue for spire job in install
Cray-HPE/docs-csm pull request #4696
Opened 2024-02-12 18:39 UTC by ndavidson-hpe

# Description

Adds in a known issue where the cray-spire-update-bss job is deleted after some time. The workaround is to recreate the job from the helm chart and restart to ensure the steps are correct.\

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-02-12 19:17 UTC, rustydb requested changes

2024-02-12 19:17 UTC, rustydb commented on install/install_csm_services.md
The indentation is breaking the ordered list and formtting.

![image](https://github.com/Cray-HPE/docs-csm/assets/7772179/8ee8ff4e-d00b-4390-841c-20d07e7525f8)

For anything that's apart of a list item, it should be indented to at least the first character in the first line.

e.g.

````markdown
1. Lorem ipsom

   Another statement, aligned with "L"

1. Another step

   ```bash
   echo "hello world"
   ```

````

2024-02-12 19:35 UTC, ndavidson-hpe commented on install/install_csm_services.md
Will fix.

2024-02-13 20:06 UTC, rustydb commented on install/install_csm_services.md
> +```
````suggestion
     The Following error may occur during `Create base BSS global boot parameters` step:

     ```text
     kubectl -n spire get "${SPIRE_JOB}" -o json | jq 'del(.spec.selector)' \
     >     | jq 'del(.spec.template.metadata.labels."controller-uid")' \
     >     | kubectl replace --force -f -
     error: the server doesn't have a resource type ""
     No resources found
     error: no objects passed to replace
     ```
````

2024-02-13 20:07 UTC, rustydb commented on install/install_csm_services.md
> +     ```
````suggestion
   The Following error may occur during `Create base BSS global boot parameters` step:

   ```text
   kubectl -n spire get "${SPIRE_JOB}" -o json | jq 'del(.spec.selector)' \
   >     | jq 'del(.spec.template.metadata.labels."controller-uid")' \
   >     | kubectl replace --force -f -
   error: the server doesn't have a resource type ""
   No resources found
   error: no objects passed to replace
   ```
````

2024-02-13 20:07 UTC, rustydb approved these changes

2024-02-13 21:16 UTC, heemstra approved these changes

2024-02-13 22:46 UTC, merged