CASMINST-3004
Cray-HPE/docs-csm pull request #47
Opened 2021-09-17 18:22 UTC by lukebates123

Remove unnecessary instructions related to BGP that may cause confusion.

2021-09-20 15:50 UTC, johren-hpe commented
This is removing the step to clear the BGP sessions.   We still need those steps included.

2021-09-20 17:51 UTC, johren-hpe commented on install/deploy_management_nodes.md
> -1. If the neighbor IP addresses do not match the worker NCN IP addresses, use the helper script for Mellanox and CANU (Cray Automated Network Utility) for Aruba.
Response from Luke in slack:
when the bgp script runs it wipes out the previous bgp config and then overwrites, so if we’re having them do that everytime I think the clear BGP neighbors shoudn’t be necessary.

2021-09-20 17:51 UTC, johren-hpe commented on install/deploy_management_nodes.md
> -1. If the neighbor IP addresses do not match the worker NCN IP addresses, use the helper script for Mellanox and CANU (Cray Automated Network Utility) for Aruba.
If that is the case that we always wipe out the previous config, I think we should be okay regarding BGP session reset.   
However, I think we should still have the steps above to tell them how to find the IP addresses for the switches, right?

2021-09-20 18:02 UTC, johren-hpe commented on install/deploy_management_nodes.md
> -1. If the neighbor IP addresses do not match the worker NCN IP addresses, use the helper script for Mellanox and CANU (Cray Automated Network Utility) for Aruba.
We also need SYSTEM_NAME for the paths arguments in the helper script and CANU commands below.

2021-09-20 18:15 UTC, lukebates123 commented on install/deploy_management_nodes.md
> -1. If the neighbor IP addresses do not match the worker NCN IP addresses, use the helper script for Mellanox and CANU (Cray Automated Network Utility) for Aruba.
Added back the steps to get the switch IPs.

2021-09-20 19:08 UTC, johren-hpe commented on install/deploy_management_nodes.md
> +      pit# grep -B1 "name: ncn-w" /var/www/ephemeral/prep/${SYSTEM_NAME}/networks/NMN.yaml
Do we need the worker NCN IPs still?

2021-09-20 19:14 UTC, johren-hpe commented on install/deploy_management_nodes.md
> +      pit# grep -B1 "name: ncn-w" /var/www/ephemeral/prep/${SYSTEM_NAME}/networks/NMN.yaml
I see now after expanding below that we need them for the step of checking the status.

2021-09-20 19:16 UTC, johren-hpe requested changes

2021-09-20 19:16 UTC, johren-hpe commented on install/deploy_management_nodes.md
> -    1. Log in to the switch as the `admin` user:
I think we'll need this login step below where we are telling them to check the status on the switch (after running the helper script or canu).

2021-09-20 21:01 UTC, johren-hpe approved these changes

2021-09-21 20:16 UTC, denniswalker approved these changes

2021-09-21 20:16 UTC, merged