CASMINST-6574 CASMTRIAGE-6772 FAS new updates
Cray-HPE/docs-csm pull request #4857
Opened 2024-03-19 18:38 UTC by mbuchmann-hpe

# Description

Updated release notes with check_bios_firmware script issue.

Added issues in the known issues folder.

Added steps to Gigabyte updating M001 BMC/BIOS to check for completion.

Change to executable backup_smd_posgres.sh

PRs:
- CASMINST-6574
- CASMTRIAGE-6772

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-03-19 18:41 UTC, mbuchmann-hpe commented
The two checks that are failing are on a script that all I changed was the permissions on to make it executable, will not be making any changes to the script as that would require revalidation of that script.

2024-03-19 19:03 UTC, jwlv requested changes
Is the license check and shmft checks expected to fail?

2024-03-19 19:06 UTC, mbuchmann-hpe commented
> Is the license check and shmft checks expected to fail?

I am ignoring the failings because the script permissions were the only thing that changed and I did not want to change the script any to avoid have to revalidate the script.

2024-03-19 19:14 UTC, nrockershousen approved these changes

2024-03-19 19:14 UTC, nrockershousen commented on operations/firmware/Updating_Firmware_m001.md
> +    Wait for the BMC to update and reboot
```suggestion
    Wait for the BMC to update and reboot:
```

2024-03-19 19:14 UTC, nrockershousen commented on troubleshooting/known_issues/cray-tftp-upload.md
> +***Workaround:*** Edit the script `/usr/local/bin/cray-tftp-upload` Changing this line:
```suggestion
***Workaround:*** Edit the script `/usr/local/bin/cray-tftp-upload`, changing the following line:

```

2024-03-19 19:14 UTC, nrockershousen commented on troubleshooting/known_issues/cray-tftp-upload.md
> +If you receive the following type of error please apply the workaround:
```suggestion
If you receive the following type of error, then apply the workaround:

```

2024-03-19 19:15 UTC, rustydb approved these changes

2024-03-19 19:24 UTC, jwlv approved these changes

2024-03-19 19:33 UTC, shunr-hpe approved these changes

2024-03-20 19:03 UTC, rustydb commented
/backport release/1.6

2024-03-20 19:05 UTC, merged