CASMHMS-6189 - Update for fixes to Rapid Restore procedures for release/1.4
Cray-HPE/docs-csm pull request #4935
Opened 2024-04-10 20:22 UTC by mbuchmann-hpe

# Description

Minor updates to docs and scripts for the Rapid Restore Procedures

CASMHMS-6189

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

2024-04-10 20:28 UTC, mbuchmann-hpe commented
Do not listen to the shellcheck error - this is how it broke the script

2024-04-11 13:32 UTC, jwlv requested changes

2024-04-11 13:32 UTC, jwlv commented on scripts/operations/boot_script_service/bss-restore-bootparameters.sh
> +for i in $@; do
It looks like the shellcheck job is failing because of this change:

> In scripts/operations/boot_script_service/bss-restore-bootparameters.sh line 63:
> for i in $@; do
>          ^-- SC206[8](https://github.com/Cray-HPE/docs-csm/actions/runs/8638212380/job/23682159041?pr=4935#step:5:9) (error): Double quote array expansions to avoid re-splitting elements.

2024-04-11 20:30 UTC, jwlv approved these changes

2024-04-12 19:19 UTC, rustydb approved these changes

2024-04-12 19:19 UTC, merged