Updates to Rapid procedures for release/1.5
Cray-HPE/docs-csm pull request #4936
Opened 2024-04-10 20:43 UTC by mbuchmann-hpe

# Description

Minor updates to docs and scripts for the Rapid Restore Procedures
Moved HSM scripts to correct location

CASMHMS-6189

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

2024-04-10 20:46 UTC, mbuchmann-hpe commented
Ignoring failing script checks - Scripts are good.

2024-04-11 13:32 UTC, jwlv requested changes

2024-04-11 13:32 UTC, jwlv commented on scripts/operations/hardware_state_manager/backup_smd_postgres.sh
license-check is failing for this file due to not having a copyright year.

2024-04-11 13:32 UTC, jwlv commented on scripts/operations/hardware_state_manager/backup_smd_postgres.sh
Additionally, the mvdan/shfmt check is failing in some way related to this file but looking at the output I have no idea why...

2024-04-11 14:56 UTC, mbuchmann-hpe commented on scripts/operations/hardware_state_manager/backup_smd_postgres.sh
Updated

2024-04-11 14:57 UTC, mbuchmann-hpe commented on scripts/operations/hardware_state_manager/backup_smd_postgres.sh
It does not like the indenting in the script.

2024-04-11 20:31 UTC, jwlv approved these changes

2024-04-12 19:19 UTC, rustydb approved these changes

2024-04-12 19:19 UTC, merged