CASMTRIAGE CASMTRIAGE-6844 1.3 : DOCS: cray-console-data-postgres has leader but start failed
Cray-HPE/docs-csm pull request #5005
Opened 2024-04-19 21:33 UTC by kimjensen-hpe

# Description
Resolve CASMTRIAGE-6844 for release/1.3

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-04-19 21:50 UTC, bo-quan requested changes

2024-04-19 21:50 UTC, bo-quan commented on operations/kubernetes/Troubleshoot_Postgres_Database.md
> +  - [Recover start failed member](#recover-from-a-start-failed-member)
```suggestion
  - [Recover from a start failed member](#recover-from-a-start-failed-member)
```

2024-04-19 21:50 UTC, bo-quan commented on operations/kubernetes/Troubleshoot_Postgres_Database.md
> +### Recover from a start failed
```suggestion
### Recover from a start failed member
```

2024-04-19 21:56 UTC, bo-quan approved these changes

2024-04-19 21:56 UTC, kimjensen-hpe commented on operations/kubernetes/Troubleshoot_Postgres_Database.md
> +  - [Recover start failed member](#recover-from-a-start-failed-member)
fixed

2024-04-19 21:57 UTC, kimjensen-hpe commented on operations/kubernetes/Troubleshoot_Postgres_Database.md
> +### Recover from a start failed
fixed

2024-04-22 15:26 UTC, rustydb approved these changes

2024-04-23 19:06 UTC, merged