TECHPUBS-4214: Corrected references to Slingshot documentation (1.5)
Cray-HPE/docs-csm pull request #5036
Opened 2024-04-26 16:21 UTC by nrockershousen

# Description

Fixing several section and document titles for Slingshot.
Moving Slingshot switch firmware update to correct IUF stage.

https://jira-pro.it.hpe.com:8443/browse/TECHPUBS-4214

Relates to:
- https://github.com/Cray-HPE/docs-csm/pull/5035 

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-04-29 17:11 UTC, kgarima123 approved these changes

2024-04-30 19:17 UTC, rustydb approved these changes

2024-04-30 19:18 UTC, rustydb commented
Waiting on merging this one https://github.com/Cray-HPE/docs-csm/pull/5045

2024-05-01 17:24 UTC, mharding-hpe commented on operations/iuf/workflows/configuration_of_SFM.md
> +in the “Install Slingshot software in a CSM environment” section of the _HPE Slingshot Operations Guide_.
```suggestion
in the "Install Slingshot software in a CSM environment" section of the _HPE Slingshot Operations Guide_.
```

2024-05-01 17:25 UTC, mharding-hpe commented on operations/iuf/workflows/configuration_of_SFM.md
> +the “Installing 200Gbps NIC host software” section of the _HPE Slingshot Operations Guide_.
```suggestion
the "Installing 200Gbps NIC host software" section of the _HPE Slingshot Operations Guide_.
```

2024-05-01 20:19 UTC, mharding-hpe requested changes
The two linting comments I made should be addressed before merging

2024-05-03 17:58 UTC, rustydb commented
> The two linting comments I made should be addressed before merging

@mharding-hpe, there were two backports that merged last week; this remained open due to two merge conflicts. Do we need follow-up PRs to those other base branches?

2024-05-07 19:07 UTC, rustydb commented
> > The two linting comments I made should be addressed before merging
> 
> @mharding-hpe, there were two backports that merged last week; this remained open due to two merge conflicts. Do we need follow-up PRs to those other base branches?

nevermind, I see your comments have remarks mentioning you fixed 1.6 in https://github.com/Cray-HPE/docs-csm/pull/5064

2024-05-07 19:15 UTC, merged