CASMTRIAGE-2681: Changed hardware name from Server to Node for Gigabyte and HPE
Cray-HPE/docs-csm pull request #512
Opened 2021-11-08 13:16 UTC by haroldlongley

## Summary and Scope

CASMTRIAGE-2681: Changed hardware name from Server to Node for Gigabyte and HPE

Software in the system has client/server relationship.  But calling a compute node a compute "server" causes confusion about the role of the component.

A server can be standalone.  A node is part of a collection of components such as a supercomputer.

## Issues and Related PRs

## Testing

### Tested on:

### Test description:

## Risks and Mitigations

## Pull Request Checklist

2021-11-08 16:46 UTC, nrockershousen commented on operations/node_management/Update_the_Gigabyte_Node_BIOS_Time.md
> +## Update the Gigabyte Node BIOS Time
An entry for this file should be added to the Node Management section in the /operations/index.md file.

2021-11-10 18:42 UTC, denniswalker commented
/backport staging/1.0.1 release/1.2 main

2022-04-27 23:31 UTC, mharding-hpe requested changes
Friendly housekeeping note! This needs to be rebased/cherry-picked before it can be reviewed. Or (given the age of this PR), if the change is no longer needed or applicable, please close this badboy.

2022-07-18 19:15 UTC, rustydb commented
Closing this PR, it is stale and the JIRA is either incorrect or has been moved (I Can't find CASMTRIAGE-2681).

2022-07-18 19:15 UTC, closed without merging