Casminst 6894
Cray-HPE/docs-csm pull request #5172
Opened 2024-06-18 22:24 UTC by rustydb

# Description

Fixes CASMINST-6429. Bundles the new DST GPG key into docs-csm as well as a function for importing it into the NCN images during fresh installs and upgrades.

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-06-18 22:37 UTC, mtupitsyn approved these changes

2024-06-20 17:55 UTC, leliasen-hpe approved these changes

2024-06-20 20:55 UTC, mtupitsyn commented on scripts/operations/node_management/ncn-image-modification.sh
> +  gpg_keys_path="${scripts_path}/keys"
This way `gpg_keys_path` will be evaluated to `/usr/share/doc/csm/scripts/operations/node_management/keys`. It's actually one level up (`/usr/share/doc/csm/scripts/operations/keys/`).

2024-06-20 21:10 UTC, mtupitsyn requested changes
Please adjust keys directory path.

2024-06-24 16:21 UTC, mtupitsyn approved these changes

2024-06-24 16:22 UTC, merged