STP-3044: NCN Rebuild procedures
Cray-HPE/docs-csm pull request #526
Opened 2021-11-09 19:37 UTC by nrockershousen

## Summary and Scope

Improved workflow of NCN Rebuild procedures. Updated file names to match title names. Minor formatting and style changes.

This change only applies to the release/1.0 branch.

## Issues and Related PRs

Resolves [STP-3044](https://connect.us.cray.com/jira/browse/STP-3044)

## Testing

N/A

### Tested on:

N/A

### Test description:

N/A

## Risks and Mitigations

N/A

2021-11-15 14:19 UTC, bklei approved these changes

2021-11-15 20:56 UTC, denniswalker commented
/backport release/1.1 release/1.2 main

2022-04-27 23:30 UTC, mharding-hpe requested changes
Friendly housekeeping note! This needs to be rebased/cherry-picked before it can be reviewed. Or (given the age of this PR), if the change is no longer needed or applicable, please close this badboy.

2022-04-28 13:13 UTC, nrockershousen commented
This content has changed quite a bit since this was opened. I will close this and can open a new ticket/PR if needed.

2022-04-28 13:13 UTC, closed without merging