CASMTRIAGE-7120 - PostgreSQL cannot set transaction read-write mode during recovery errors
Cray-HPE/docs-csm pull request #5396
Opened 2024-09-25 10:49 UTC by spillerc-hpe

# Description

When a control-plane node is rebooted it is possible to end up in a state where the PostgreSQL database has changed leader without the client noticing causing the client to continue sending read-write transactions to the former leader which is now a read-only replica.

This change updates the documentation to make it clear that this problem can occur to any of the PostgreSQL clusters, not just spire and documents a mitigation for this problem.

# Checklist

- [X] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [X] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-09-25 10:57 UTC, spillerc-hpe commented
/backport release/1.5

2024-09-26 14:31 UTC, kimjensen-hpe requested changes

2024-09-26 14:31 UTC, kimjensen-hpe commented on troubleshooting/known_issues/postgres_database_recovery.md
> +      kubectl -n spire rollout restart statefulset cray-sls-postgres
cray-sls-postgres is in the services namespace, not the spire namespace

2024-09-26 16:28 UTC, kimjensen-hpe approved these changes

2024-09-27 19:07 UTC, rustydb approved these changes

2024-09-27 19:07 UTC, merged