CASMCMS-9162: Add BOS option: cfs-read-timeout
Cray-HPE/docs-csm pull request #5475
Opened 2024-10-16 19:06 UTC by jsollom-hpe

# Description

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-10-22 14:32 UTC, mharding-hpe requested changes
Since this currently is only going into CSM 1.5 as a hotfix, I would recommend NOT updating the 1.5 docs. Or if you do, we need to be very clear that the relevant option is only available if they have the specific hotfix applied.

2024-11-22 20:52 UTC, jsollom-hpe commented on operations/boot_orchestration/Options.md
> +
```suggestion
Note: This option is only available is a 'hotfix' in CSM-1.5.
```

2024-11-22 20:53 UTC, jsollom-hpe commented on operations/boot_orchestration/Options.md
> +Note: This option is only available is a 'hotfix' in CSM-1.5.
```suggestion
    Note: This option is only available is a 'hotfix' in CSM-1.5.
```

2024-11-22 20:53 UTC, jsollom-hpe commented on operations/boot_orchestration/Options.md
> +    Note: This option is only available is a 'hotfix' in CSM-1.5.
```suggestion
    Note: This option is only available as a 'hotfix' in CSM-1.5.
```

2024-11-22 21:25 UTC, mharding-hpe commented on operations/boot_orchestration/Options.md
> +    Note: This option is only available as a 'hotfix' in CSM-1.5.
```suggestion
    Note: This option is only available as a 'hotfix' in CSM-1.5.

```

2024-11-22 22:08 UTC, mharding-hpe approved these changes

2025-01-07 23:10 UTC, mharding-hpe commented
/backport release/1.4

2025-01-15 22:05 UTC, mtupitsyn approved these changes

2025-01-15 22:05 UTC, merged