CASM-4713 Remove prometheus logging
Cray-HPE/docs-csm pull request #5551
Opened 2024-11-19 04:19 UTC by Srinivas-Anand-HPE

# Description

CASM-4713 Remove prometheus logging

1. To remove prometheus metrics from Main Step since main container need to run remaining operations required only prometheus metrics is removed

2. To remove prom-metrics Step since prom-metrics pod is intented to run only prometheus metrics and remaining operations are for data in metics

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [X] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-11-27 06:28 UTC, leliasen-hpe approved these changes

2024-11-27 06:48 UTC, Pankhuri-Rajesh approved these changes

2024-11-27 06:48 UTC, Pankhuri-Rajesh commented on workflows/iuf/operations/extract-release-distributions.yaml
> +
I see empty lines at 86-88. Do you need 3 line spaces? If not, then you can remove accordingly

2024-11-27 07:00 UTC, rajeshranganathan-hpe approved these changes

2024-12-04 16:49 UTC, leliasen-hpe requested changes
These changes should be merged to branch feature/iuf-improvements-1.6.1 for further testing, not to release/1.6

2025-01-08 12:30 UTC, closed without merging