USS-2561: Document USS-2025 workaround for USS 1.2
Cray-HPE/docs-csm pull request #5554
Opened 2024-11-20 18:53 UTC by vinaybabug-hpe

Commit Change:
* Add note to modify munge uid and gid for version cray/munge-munge:1.6.0

# Description

# Checklist

- [x] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [x] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [x] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-11-22 20:18 UTC, rustydb requested changes

2024-11-22 20:18 UTC, rustydb commented on operations/multi-tenancy/Create_a_Tenant.md
> +- Please set spec.munge.uid to 498 and spec.munge.gid to 484 if using munger container version cray/munge-munge:1.6.0
Remove trailing space on `**Note:**` and I suggest using a block comment to callout the note.
```suggestion
> **Note:**
> - Container versions must be customized to the versions installed on the system
> - Please set spec.munge.uid to 498 and spec.munge.gid to 484 if using munger container version cray/munge-munge:1.6.0
```

2024-11-26 21:20 UTC, rustydb approved these changes

2024-11-27 18:39 UTC, vinaybabug-hpe commented
I can use some help to resolve this Check Licenses failure.

2024-12-02 22:35 UTC, don-bahls-hpe approved these changes

2024-12-03 16:40 UTC, merged