HPCCHT3-5144: Add note for upgrade path.
Cray-HPE/docs-csm pull request #5595
Opened 2024-12-10 17:24 UTC by zimmer-hpe

It would be convenient for admins if they knew to look at the previous sdu.conf.

# Description

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-12-17 20:02 UTC, rustydb approved these changes

2025-01-06 22:02 UTC, zimmer-hpe commented
Anything else I need to do for this?

2025-01-07 15:55 UTC, bo-quan requested changes

2025-01-07 15:55 UTC, bo-quan commented on operations/iuf/workflows/configuration.md
> +    - If this an upgrade you can refer to or copy in the stored the backup you created in the [Preparation](preparation.md#3-save-system-state-before-upgrade) step.
```suggestion
    - If this is an upgrade, you can refer to or copy from the stored backup you created in the [Preparation](preparation.md#4-save-system-state-before-upgrade) step.
```

2025-01-07 16:57 UTC, zimmer-hpe commented on operations/iuf/workflows/configuration.md
> +    - If this an upgrade you can refer to or copy in the stored the backup you created in the [Preparation](preparation.md#3-save-system-state-before-upgrade) step.
Ok done

2025-01-08 16:18 UTC, bo-quan approved these changes

2025-01-10 20:04 UTC, zimmer-hpe commented
Is this in a mergable state?

2025-01-13 18:18 UTC, zimmer-hpe commented
@haroldlongley I think this should resolve what your looking for.

2025-01-15 04:42 UTC, zimmer-hpe commented
/backport release/1.7

2025-01-21 20:10 UTC, merged