Update release notes for 1.6.0
Cray-HPE/docs-csm pull request #5604
Opened 2024-12-17 19:09 UTC by rustydb

# Description

# Checklist

- [ ] If I added any command snippets, the steps they belong to follow the prompt conventions (see [example][1]).
- [ ] If I added a new directory, I also updated `.github/CODEOWNERS` with the corresponding team in [Cray-HPE][2].
- [ ] My commits or Pull-Request Title contain my JIRA information, or I do not have a JIRA.

 
[1]: https://github.com/Cray-HPE/docs-csm/blob/main/introduction/documentation_conventions.md#using-prompts
[2]: https://github.com/Cray-HPE/teams

2024-12-19 20:40 UTC, rustydb commented
There are numerous spellcheck issues due to the copy-paste of JIRAs. Talking with @nrockershousen on how to resolve.

2025-01-08 19:12 UTC, mharding-hpe requested changes

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +For a list of all features with an announced removal target,
BOS v1 is removed in CSM 1.6 -- we do not want to remove this from the release notes.

```suggestion
* [BOS](glossary.md#boot-orchestration-service-bos) v1

For a list of all features with an announced removal target,
```

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +    * CAST-36629: cray-hms-smd-test-functional regex does not match
I'm not sure "New software support" is the right heading for the resolved CASTs.
For the BOS one, we added a new BOS v2 option, so I guess it's kind of new software. I am not familiar with the HMS one, but it sounds like a bug fix.

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +    * v1 of Power Control Service (PCS) is active.
Are these meant to be sub-bullets of the above iSCSI bullet? They don't seem related to iSCSI.

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +* Significant resource utilization improvements in the PCS, FAS, hmcollector, and SMD services which will reduce pod restarts and improve overall functionality.
```suggestion
* Significant resource utilization improvements in the PCS, FAS, hmcollector, and SMD services which will reduce pod restarts and improve overall functionality.

### Scale improvements

* Significant performance improvements in BOS and CFS on large scale systems.
```

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
>      * If the image to be projected does not have an `etag`
```suggestion
* iSCSI based boot content projection may fail if the image to be projected does not have an `etag`
```

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +        * A workaround is presented in [iSCSI SBPS boot failure](https://github.com/Cray-HPE/docs-csm/blob/release/1.6/troubleshooting/known_issues/SBPS_boot_fail.md)
I don't think this should be indented over further. Also, the link should be relative.
```suggestion
    * A workaround is presented in [iSCSI SBPS boot failure](troubleshooting/known_issues/SBPS_boot_fail.md)
```

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +* Please see [iSCSI SBPS](https://github.com/Cray-HPE/docs-csm/blob/release/1.6/operations/iscsi_sbps/iscsi_sbps.md) for
```suggestion
* See [iSCSI SBPS](operations/iscsi_sbps/iscsi_sbps.md) for
```

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +* `>`75% reduction in OS noise generated by the heartbeat client that runs on compute nodes.
```suggestion
* More than 75% reduction in OS noise generated by the heartbeat client that runs on compute nodes.
```

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
>  * The SAT documentation moved to be fully included within the [System Admin Toolkit (SAT)](https://cray-hpe.github.io/docs-csm/en-16/operations/system_admin_toolkit/) section of the [CSM Administrati
```suggestion
* The SAT documentation moved to be fully included within the [System Admin Toolkit (SAT)](operations/system_admin_toolkit/README.md) section of the [CSM Administration Guide](operations/README.md).
```

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +CASMPET-6748 boto3 calls to <https://rgw-vip.nmn> fail even when verify cert == false
```suggestion
CASMPET-6748 boto3 calls to `https://rgw-vip.nmn` fail even when verify cert == false
```

2025-01-08 19:12 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +CASMINST-5799 Replace remaining references to <https://artifactory.algol60.net> in docs for CSM tarball and docs RPM downloads
```suggestion
CASMINST-5799 Replace remaining references to `https://artifactory.algol60.net` in docs for CSM tarball and docs RPM downloads
```

2025-01-08 19:14 UTC, mharding-hpe commented
I will work on addressing some of the linting issues.

2025-01-08 19:47 UTC, mharding-hpe commented
> There are numerous spellcheck issues due to the copy-paste of JIRAs. Talking with @nrockershousen on how to resolve.

From what I understand, it was commanded from on high that we include a comprehensive list of every ticket that went into the release. I will not bother debating the wisdom or optics of this, and just note that I feel like we are left with two options:

1. Just throw it all inside a text block and call it a day, so the markdown/linting/etc issues will be moot.
2. Go through and edit them all to fix them properly.

I don't think any of us have the time to do the second one, especially if we extend it to actually making the Jira listing make sense to someone who doesn't have access to go read the Jira itself. But if we aren't going to bother to do that, then it seems a fool's errand to worry about placating the linter, as it would be just putting the proverbial lipstick on a pig.

So I went ahead and did the former, at least for the giant list of tickets at the end of the release notes. I probably should have done it for the documentation ticket list as well, because many of those are equally incomprehensible to a reader, but I had already edited them to placate the linter before I came to the above conclusions.

Side-note -- we also don't make much distinction in this page between things that are new in CSM 1.6 and do not appear in any previous patch release, versus things which were not in CSM 1.5, but got added in CSM 1.5.X, and also show up in CSM 1.6.0. As best I can tell, we're including both of these on this page, even though for anyone who was previous running CSM 1.5, they are almost certainly on one of the patch versions, meaning that a lot of stuff on this page won't truly be new. But that's not getting solved in this PR.

2025-01-08 19:48 UTC, mharding-hpe approved these changes

2025-01-08 19:50 UTC, mharding-hpe commented on RELEASE_NOTES.md
> +| Platform Component           | Version |
I did not verify if these versions are actually accurate for CSM 1.6.0. I'm assuming the teams who own these will do that / have done that.

2025-01-15 12:07 UTC, spillerc-hpe commented on RELEASE_NOTES.md
> +* Bond HSN MAC VLAN interfaces support Slingshot resiliency
MAC VLAN should be `macvlan` as it's a specific virtual interface type.

2025-01-15 12:10 UTC, spillerc-hpe commented on RELEASE_NOTES.md
> +| `bitnami-etcd` on `ncn-mxxx` | 3.5.0   |
We don't use bitnami etcd on the master nodes, just plain ol' etcd.

bitnami is just the vendor of the helm chart we use to deploy etcd inside the cluster.

2025-01-15 12:14 UTC, spillerc-hpe commented on RELEASE_NOTES.md
>  ## Known issues
I think we should call out the postgres failover issue here.

troubleshooting/known_issues/postgres_database_recovery.md

Neither workaround fully solves the problem, an upgrade of the postgresql components is needed and whenever a master node is rebooted or rebuilt there is a chance that postgresql will failover without the clients noticing resulting in services behaving strangely.

2025-01-15 16:07 UTC, jpdavis-prof commented
We should add the ARP cache tuning guide. https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-6736
I'm guessing it should go in Documentation Enhancements.

2025-01-16 20:56 UTC, manderson-hpe approved these changes

2025-01-16 21:44 UTC, mharding-hpe approved these changes

2025-01-16 22:00 UTC, spillerc-hpe commented on RELEASE_NOTES.md
>  ## Known issues
I added this information to the document.

2025-01-16 22:26 UTC, merged