CASMTRIAGE-2096: Clarify Kubernetes NCNs in topics and add glossary entry csm 1.2
Cray-HPE/docs-csm pull request #57
Opened 2021-09-20 22:37 UTC by haroldlongley

CASMTRIAGE-2096: Clarify Kubernetes NCNs in topics and add glossary entry csm 1.2

2022-04-27 23:33 UTC, mharding-hpe requested changes
Friendly housekeeping note! This needs to be rebased/cherry-picked against the new main branch before it can be reviewed. Or (given the age of this PR), if the change is no longer needed or applicable, please close this badboy.

2022-05-04 17:44 UTC, rustydb approved these changes

2022-06-06 19:24 UTC, rustydb commented
This is actually tied to https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3016
The JIRA linked here routes to Cray JIRA and the JIRA has moved, so the link is broken.

2022-06-16 17:39 UTC, mharding-hpe requested changes
I will see if I can resolve the merge conflicts and linting errors.

2022-06-16 17:39 UTC, mharding-hpe commented on glossary.md
> +(ncn-mXXX) or Kubernetes worker nodes (ncn-wXXX). The only type of management node which is
```suggestion
(`ncn-mXXX`) or Kubernetes worker nodes (`ncn-wXXX`). The only type of management node which is
```

2022-06-16 17:39 UTC, mharding-hpe commented on glossary.md
> +excluded from this is the utility storage node (ncn-sXXX).
```suggestion
excluded from this is the utility storage node (`ncn-sXXX`).
```

2022-06-16 17:39 UTC, mharding-hpe commented on operations/spire/Restore_Spire_Postgres_without_a_Backup.md
> +3. Disable spire-agent on all of the Kubernetes NCNs (all worker nodes and master nodes) and delete the join data.
```suggestion
3. Disable `spire-agent` on all of the Kubernetes NCNs (all worker nodes and master nodes) and delete the join data.
```

2022-06-16 17:45 UTC, mharding-hpe commented
It appears that all of the originally proposed changes already exist in the 1.2 branch, so I'm closing this PR.

2022-06-16 17:45 UTC, closed without merging