CASMPET-4709
Cray-HPE/docs-csm pull request #669
Opened 2021-12-15 23:34 UTC by leliasen-hpe

## Summary and Scope

Replaced Postgres Health Check in worker upgrade script with scripts used in postgres goss tests.

Backwards compatible

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:
 * wasp
  * Needs More Testing

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2021-12-15 23:44 UTC, bklei approved these changes

2022-04-27 23:26 UTC, mharding-hpe requested changes
Friendly housekeeping note! This needs to be rebased before it can be reviewed. Or (given the age of this PR), if the change is no longer needed or applicable, please close this badboy.

2022-06-10 18:47 UTC, rustydb approved these changes

2022-06-16 17:47 UTC, mharding-hpe requested changes
The merge conflicts need to be resolved before I can review this

2022-06-16 20:24 UTC, closed without merging

2022-06-16 20:24 UTC, bklei commented
This can be closed - the postgres health checks have been integrated into csi pit validate --postgres
https://github.com/Cray-HPE/docs-csm/blob/release/1.2/upgrade/1.2/scripts/upgrade/ncn-upgrade-worker-nodes.sh#L81-L92 (edited)