CASMINST-2951-1.2 Correct large DNS and FIXME sections which were mistakenly removed
Cray-HPE/docs-csm pull request #747
Opened 2022-01-12 19:54 UTC by haroldlongley

## Summary and Scope

CASMINST-2951-1.2 Correct large DNS and FIXME sections which were mistakenly removed

The previous mod to CASMINST-2951 mistakenly removed major DNS and FIXME sections and had used the old dtr.dev.cray.com URL in many places.

## Issues and Related PRs

## Testing

### Tested on:

### Test description:

## Risks and Mitigations

## Pull Request Checklist

2022-04-27 23:23 UTC, mharding-hpe requested changes
This needs to be rebased before it can be reviewed.

2022-06-07 17:54 UTC, mharding-hpe commented
@haroldlongley is this PR still needed?

2022-06-10 18:48 UTC, rustydb requested changes

2022-06-10 18:48 UTC, rustydb commented on install/prepare_site_init.md
> +       linux# export LDAP=dcldap2.us.cray.com
Can you pretty please remove the `linux#` prompts? If this needs to be ran on an _external_ machine, use `external#` but with the new `main` branch convention: https://github.com/Cray-HPE/docs-csm/blob/MTL-1695/introduction/documentation_conventions.md#step-examples

2022-06-27 15:41 UTC, mharding-hpe commented
This PR is no longer needed. Closing it out.

2022-06-27 15:41 UTC, closed without merging