CASMPET-5341 1.0 : Skeleton DOC procedures for Add Remove Replace NCN
Cray-HPE/docs-csm pull request #931
Opened 2022-02-18 19:49 UTC by kimjensen-hpe

## Summary and Scope

Adds alpha framework doc for Add, Remove, Replace NCNs

## Issues and Related PRs

* Resolves [CASMPET-5341](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5341)
* Change will also be needed in NA
* Future work required by [CASM-2769](https://jira-pro.its.hpecorp.net:8443/browse/CASM-2769)
* Documentation changes required in NA
* Merge with/before/after NA

## Testing

NA

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-02-18 20:56 UTC, rgross727 approved these changes

2022-02-22 15:52 UTC, nrockershousen commented
We should add these new files to the operations index.md file: https://github.com/Cray-HPE/docs-csm/blob/release/1.2/operations/index.md#node-management

2022-02-25 15:01 UTC, cdelatte-hpe requested changes

2022-02-25 15:01 UTC, cdelatte-hpe commented on operations/node_management/Add_Remove_Replace_NCNs.md
> +# Add Worker, Storage or Master NCNs
I don't think you can have a # top level followed by another # top level.

2022-02-25 15:01 UTC, cdelatte-hpe commented on operations/node_management/Add_Remove_Replace_NCNs.md
> +# Remove Worker, Storage or Master NCNs
Same top level issue like commented above

2022-02-25 15:01 UTC, cdelatte-hpe commented on operations/node_management/Add_Remove_Replace_NCNs.md
> +# Replace Worker, Storage or Master NCNs
top level same as above

2022-02-25 15:04 UTC, bklei approved these changes

2022-02-25 15:26 UTC, cdelatte-hpe approved these changes

2022-02-25 16:52 UTC, rgross727 approved these changes

2022-02-25 17:14 UTC, merged