TECHPUBS-3096-1.2: Added pre-requisite in set_gigabyte_node_bmc_to_fact…
Cray-HPE/docs-csm pull request #942
Opened 2022-02-22 18:49 UTC by jimostrom-hpe

## Gigabyte scripts on LiveCD

Added prerequsite in set_gigabyte_node_bmc_to_factory_defaults.md that scripts are available only in PIT environment and can be copied from LiveCD

Backwards compatible bugfix

## Issues and Related PRs

TECHPUBS-3096-1.2

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ X] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-04-27 23:16 UTC, mharding-hpe requested changes

2022-04-27 23:16 UTC, mharding-hpe commented on install/set_gigabyte_node_bmc_to_factory_defaults.md
> +**Note**: This section refers to scripts that exist only in the PIT environment.  If necessary, copy the LiveCD data from a different machine to get these scripts.
```suggestion
**Note**: This section refers to scripts that exist only in the PIT environment. If necessary, copy the LiveCD data from a different machine to get these scripts.
```

2022-04-27 23:17 UTC, mharding-hpe approved these changes

2022-04-27 23:18 UTC, mharding-hpe commented
/backport release/1.2

2022-05-10 19:03 UTC, nrockershousen approved these changes

2022-05-10 19:13 UTC, jimostrom-hpe commented
/backport release/1.0

2022-05-10 19:14 UTC, merged