CASMCMS-7676 Add documentation for IMS recipe templating
Cray-HPE/docs-csm pull request #974
Opened 2022-02-25 21:11 UTC by ecozzi-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

Add docs for creating IMS recipes that get templated during IMS create jobs. 

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
Yes

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASMCMS-7676](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-7676)

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable
- [ ] Do not merge until CSM 1.2.5 content can be merged.

2022-03-16 14:08 UTC, rkleinman-hpe requested changes

2022-03-16 14:08 UTC, rkleinman-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +ncn# i logs cray-ims-812e9cda-62a8-4d1b-83a3-5891340671ff-create-78z6p -c fetch-recipe
Use full commands in docs, not shortcuts.

2022-04-24 00:17 UTC, mharding-hpe requested changes

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +1. Add a file named '.ims_recipe_template.yaml' to the root of the recipe archive.
```suggestion
1. Add a file named `.ims_recipe_template.yaml` to the root of the recipe archive. 
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +   ``` bash
```suggestion
   ```
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +   The contents of this file must be valid yaml containing the keyword `template_files`. The `template_files` keyword
```suggestion
   The contents of this file must be valid YAML, containing the keyword `template_files`. The `template_files` keyword
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +   ```
```suggestion
   ```yaml
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +   **NOTE:** Only files listed under the template_files key will be templated by IMS.
```suggestion
   **NOTE:** Only files listed under the `template_files` key will be templated by IMS. 
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +3. Create a tgz archive of the image recipe.
```suggestion
3. Create a `tgz` archive of the image recipe.
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +    ``` bash
```suggestion
    ```
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +   --link-type s3 \
```suggestion
           --link-type s3 \
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +   --link-path s3://ims/recipes/$IMS_RECIPE_ID/$ARTIFACT_FILENAME
```suggestion
           --link-path s3://ims/recipes/$IMS_RECIPE_ID/$ARTIFACT_FILENAME
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +   ``` bash
```suggestion
   ```
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +ncn# i logs cray-ims-812e9cda-62a8-4d1b-83a3-5891340671ff-create-78z6p -c fetch-recipe
```suggestion
ncn# kubectl -n ims logs cray-ims-812e9cda-62a8-4d1b-83a3-5891340671ff-create-78z6p -c fetch-recipe
```

2022-04-24 00:17 UTC, mharding-hpe commented on operations/image_management/Upload_and_Register_an_Image_Recipe.md
> +``` bash
```suggestion
```
```

2022-04-25 13:57 UTC, jsl-hpe approved these changes

2022-05-12 23:43 UTC, mharding-hpe commented
Rebased PR

2022-05-13 00:07 UTC, mharding-hpe commented
I added a couple of linting commits to resolve the failures reported by the markdown checkers.

2022-05-13 00:09 UTC, mharding-hpe approved these changes

2022-06-07 19:12 UTC, rustydb approved these changes

2022-06-07 19:12 UTC, merged